# Generated by Django 5.2.7 on 2026-08-18 01:06 — editado à mão para
# preservar os dados existentes de `assigned_to` na migração pra
# `responsaveis` (M2M): precisa existir o campo novo, copiar os dados,
# e só depois remover o antigo — nessa ordem.

from django.conf import settings
from django.db import migrations, models


def copiar_assigned_to_para_responsaveis(apps, schema_editor):
    Tarefa = apps.get_model('tarefas', 'Tarefa')
    for tarefa in Tarefa.objects.exclude(assigned_to__isnull=True):
        tarefa.responsaveis.add(tarefa.assigned_to_id)


def copiar_responsaveis_para_assigned_to(apps, schema_editor):
    """Reversão best-effort: se uma tarefa ficou com mais de um responsável
    depois da migração, o rollback só consegue guardar um (era um FK
    único) — mantém o primeiro por ordem de id."""
    Tarefa = apps.get_model('tarefas', 'Tarefa')
    for tarefa in Tarefa.objects.all():
        primeiro_id = tarefa.responsaveis.order_by('id').values_list('id', flat=True).first()
        if primeiro_id:
            tarefa.assigned_to_id = primeiro_id
            tarefa.save(update_fields=['assigned_to'])


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, help_text='Quem está responsável pela tarefa — pode ser mais de uma pessoa.', related_name='tarefas_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            copiar_assigned_to_para_responsaveis,
            copiar_responsaveis_para_assigned_to,
        ),
        migrations.RemoveIndex(
            model_name='tarefa',
            name='tarefas_tar_assigne_587bff_idx',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='assigned_to',
        ),
    ]
