# Generated by Django 5.2.7 on 2026-09-15 11:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0115_acessoprotocolo'),
        ('tarefas', '0002_remove_tarefa_tarefas_tar_assigne_587bff_idx_and_more'),
        ('usuario', '0013_usuariofuncao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RotinaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Item da rotina',
                'verbose_name_plural': 'Itens da rotina',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TarefaChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('verificado', models.BooleanField(default=False)),
                ('verificado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Item de checklist',
                'verbose_name_plural': 'Itens de checklist',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddField(
            model_name='tarefa',
            name='competencia',
            field=models.DateField(blank=True, help_text='Mês de referência da ocorrência (sempre o dia 1º).', null=True),
        ),
        migrations.CreateModel(
            name='Rotina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('dia_do_mes', models.PositiveSmallIntegerField(help_text='Em mês mais curto (ex.: dia 31 em fevereiro), cai no último dia.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('inicio', models.DateField(default=django.utils.timezone.localdate, help_text='Não gera ocorrência com data anterior a este dia (evita criar a do mês já vencida).')),
                ('ultima_competencia', models.DateField(blank=True, help_text='Último mês já gerado. Impede que a tarefa excluída do mês volte a ser criada.', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotinas', to='clientes.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotinas_criadas', to=settings.AUTH_USER_MODEL)),
                ('instancia', models.ForeignKey(blank=True, help_text='Mesma regra da Tarefa: do cliente, ou de quem criou. Vazia = só Administrador vê.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotinas', to='usuario.instancia')),
                ('responsaveis', models.ManyToManyField(blank=True, help_text='Copiados para a tarefa de cada mês.', related_name='rotinas_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rotina mensal',
                'verbose_name_plural': 'Rotinas mensais',
                'ordering': ['dia_do_mes', 'titulo'],
            },
        ),
        migrations.AddField(
            model_name='tarefa',
            name='rotina',
            field=models.ForeignKey(blank=True, help_text='Rotina mensal que gerou esta tarefa. Excluir a rotina mantém o histórico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='tarefas.rotina'),
        ),
        migrations.AddConstraint(
            model_name='tarefa',
            constraint=models.UniqueConstraint(condition=models.Q(('rotina__isnull', False)), fields=('rotina', 'competencia'), name='tarefa_uma_ocorrencia_por_mes'),
        ),
        migrations.AddField(
            model_name='rotinaitem',
            name='rotina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='tarefas.rotina'),
        ),
        migrations.AddField(
            model_name='tarefachecklistitem',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='tarefas.tarefa'),
        ),
        migrations.AddField(
            model_name='tarefachecklistitem',
            name='verificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
