# Generated by Django 5.2.7 on 2025-10-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcao_equipamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcao_equipamento',
            name='descricao',
            field=models.TextField(unique=True),
        ),
    ]
