# Generated by Django 5.2.7 on 2026-02-16 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('icone', models.CharField(default='fa-book', help_text='FontAwesome icon class', max_length=50)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria Wiki',
                'verbose_name_plural': 'Categorias Wiki',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TagWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Tag Wiki',
                'verbose_name_plural': 'Tags Wiki',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ArtigoWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('fabricante', models.CharField(choices=[('MIKROTIK', 'MikroTik'), ('CISCO', 'Cisco'), ('HUAWEI', 'Huawei'), ('JUNIPER', 'Juniper'), ('EXTREME', 'Extreme Networks'), ('HP', 'HP/Aruba'), ('DELL', 'Dell'), ('DATACOM', 'Datacom'), ('GENERICO', 'Genérico/Múltiplos')], default='GENERICO', max_length=20)),
                ('modelo_especifico', models.CharField(blank=True, help_text='Ex: RB4011, Catalyst 3750', max_length=100)),
                ('descricao_curta', models.TextField(help_text='Resumo que aparece na busca', max_length=300)),
                ('conteudo', models.TextField(help_text='Conteúdo em Markdown')),
                ('favorito', models.BooleanField(default=False)),
                ('destaque', models.BooleanField(default=False)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição (menor = primeiro)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('visualizacoes', models.IntegerField(default=0)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artigos_criados', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='wiki.categoriawiki')),
                ('tags', models.ManyToManyField(blank=True, related_name='artigos', to='wiki.tagwiki')),
            ],
            options={
                'verbose_name': 'Artigo Wiki',
                'verbose_name_plural': 'Artigos Wiki',
                'ordering': ['-destaque', '-favorito', 'ordem', '-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='AnexoWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='wiki/anexos/%Y/%m/')),
                ('descricao', models.TextField(blank=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='wiki.artigowiki')),
            ],
            options={
                'verbose_name': 'Anexo Wiki',
                'verbose_name_plural': 'Anexos Wiki',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='BlocoCodigoWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Configuração BGP, Script de Backup', max_length=200)),
                ('linguagem', models.CharField(choices=[('routeros', 'RouterOS (MikroTik)'), ('cisco', 'Cisco IOS'), ('junos', 'JunOS (Juniper)'), ('bash', 'Bash/Shell'), ('python', 'Python'), ('javascript', 'JavaScript'), ('yaml', 'YAML'), ('json', 'JSON'), ('plaintext', 'Texto Puro')], default='routeros', max_length=20)),
                ('codigo', models.TextField()),
                ('descricao', models.TextField(blank=True, help_text='Explicação do código')),
                ('ordem', models.IntegerField(default=0)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos_codigo', to='wiki.artigowiki')),
            ],
            options={
                'verbose_name': 'Bloco de Código',
                'verbose_name_plural': 'Blocos de Código',
                'ordering': ['ordem'],
            },
        ),
    ]
