# Generated by Django 5.2.7 on 2026-07-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigowiki',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='wiki/pdfs/%Y/%m/'),
        ),
    ]
