# Generated by Django 5.2.7 on 2026-08-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_artigowiki_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigowiki',
            name='fabricante',
            field=models.CharField(choices=[('MIKROTIK', 'MikroTik'), ('CISCO', 'Cisco'), ('HUAWEI', 'Huawei'), ('JUNIPER', 'Juniper'), ('EXTREME', 'Extreme Networks'), ('HP', 'HP/Aruba'), ('DELL', 'Dell'), ('DATACOM', 'Datacom'), ('ZTE', 'ZTE'), ('FIBERHOME', 'Fiberhome'), ('PARKS', 'Parks'), ('VSOL', 'VSOL'), ('INTELBRAS', 'Intelbras'), ('RAISECOM', 'Raisecom'), ('GENERICO', 'Genérico/Múltiplos')], default='GENERICO', max_length=20),
        ),
    ]
