# Generated by Django 5.2.7 on 2026-09-24 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0117_agentconfig_janela_continuacao_wa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('local', models.CharField(blank=True, default='', help_text='Site, POP ou sala onde o rack está.', max_length=160)),
                ('altura_u', models.PositiveSmallIntegerField(default=42)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='clientes.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rack',
                'verbose_name_plural': 'Racks',
                'ordering': ['local', 'nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RackEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('router', 'Roteador'), ('switch', 'Switch'), ('olt', 'OLT'), ('firewall', 'Firewall'), ('cgnat', 'CGNAT'), ('dwdm', 'DWDM'), ('servidor', 'Servidor'), ('radio', 'Rádio / IDU'), ('patch_panel', 'Patch panel'), ('dio', 'DIO (fibra)'), ('organizador', 'Organizador'), ('bandeja', 'Bandeja'), ('pdu', 'PDU / Régua'), ('nobreak', 'Nobreak'), ('tampa', 'Tampa cega'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('nome', models.CharField(max_length=160)),
                ('u_inicial', models.PositiveSmallIntegerField(help_text='U mais baixo ocupado (U1 = base do rack).')),
                ('altura_u', models.PositiveSmallIntegerField(default=1)),
                ('face', models.CharField(choices=[('frente', 'Frente'), ('traseira', 'Traseira')], default='frente', max_length=10)),
                ('profundidade_total', models.BooleanField(default=True, help_text='Ocupa frente e traseira do U. Passivos rasos (patch panel, PDU) não.')),
                ('topologia_node_id', models.CharField(blank=True, default='', help_text='Id do node na topologia (para nodes que não são host do CRM).', max_length=80)),
                ('fabricante', models.CharField(blank=True, default='', max_length=80)),
                ('modelo', models.CharField(blank=True, default='', max_length=120)),
                ('num_portas', models.PositiveSmallIntegerField(default=0)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('acesso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posicoes_rack', to='clientes.acesso')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='racks.rack')),
            ],
            options={
                'verbose_name': 'Equipamento no rack',
                'verbose_name_plural': 'Equipamentos no rack',
                'ordering': ['rack', '-u_inicial'],
            },
        ),
        migrations.CreateModel(
            name='ConexaoFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porta_a', models.CharField(blank=True, default='', max_length=80)),
                ('porta_b', models.CharField(blank=True, default='', max_length=80)),
                ('meio', models.CharField(choices=[('fibra_sm', 'Fibra monomodo'), ('fibra_mm', 'Fibra multimodo'), ('utp', 'UTP (cobre)'), ('dac', 'DAC (twinax)'), ('aoc', 'AOC'), ('coaxial', 'Coaxial'), ('energia', 'Energia'), ('outro', 'Outro')], default='utp', max_length=12)),
                ('conector', models.CharField(blank=True, default='', max_length=12)),
                ('cor', models.CharField(blank=True, default='', help_text='Cor do cabo (hex).', max_length=9)),
                ('comprimento_m', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('identificacao', models.CharField(blank=True, default='', help_text='Etiqueta do cabo.', max_length=120)),
                ('topologia_link_id', models.CharField(blank=True, default='', max_length=80)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_fisicas', to='clientes.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('diagrama', models.ForeignKey(blank=True, help_text='Mapa da topologia onde está o enlace de origem.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clientes.topologiadiagrama')),
                ('ponta_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_a', to='racks.rackequipamento')),
                ('ponta_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_b', to='racks.rackequipamento')),
            ],
            options={
                'verbose_name': 'Conexão física',
                'verbose_name_plural': 'Conexões físicas',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='rackequipamento',
            constraint=models.UniqueConstraint(condition=models.Q(('acesso__isnull', False)), fields=('acesso',), name='rack_equip_acesso_unico'),
        ),
        migrations.AddConstraint(
            model_name='conexaofisica',
            constraint=models.UniqueConstraint(condition=models.Q(('topologia_link_id', ''), _negated=True), fields=('cliente', 'topologia_link_id'), name='conexao_fisica_link_unico'),
        ),
    ]
