# Generated by Django 5.2.7 on 2026-09-24 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0117_agentconfig_janela_continuacao_wa'),
        ('racks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conexaofisica',
            name='sincronizado',
            field=models.BooleanField(default=False, help_text='Criado pela sincronização com a topologia e nunca editado à mão: acompanha o enlace (portas, tipo, etiqueta) e some junto com ele.'),
        ),
        migrations.CreateModel(
            name='LinkSemCabo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topologia_link_id', models.CharField(max_length=80)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clientes.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enlace sem cabo',
                'verbose_name_plural': 'Enlaces sem cabo',
                'constraints': [models.UniqueConstraint(fields=('cliente', 'topologia_link_id'), name='link_sem_cabo_unico')],
            },
        ),
    ]
