# Generated by Django 5.2.7 on 2026-08-23 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('desbloqueio_conta', 'Conta desbloqueada'), ('desbloqueio_ip', 'IP desbloqueado no CRM'), ('unban_ssh', 'IP removido do fail2ban'), ('ban_ssh', 'IP banido manualmente no fail2ban')], max_length=30)),
                ('alvo', models.CharField(max_length=150)),
                ('detalhe', models.CharField(blank=True, default='', max_length=300)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_seguranca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ação de Segurança',
                'verbose_name_plural': 'Ações de Segurança',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='BloqueioLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('conta', 'Conta'), ('ip', 'Endereço IP')], default='conta', max_length=10)),
                ('chave', models.CharField(help_text='username (tipo=conta) ou endereço IP (tipo=ip).', max_length=150)),
                ('ultimo_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('falhas', models.PositiveIntegerField(default=0)),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True)),
                ('total_bloqueios', models.PositiveIntegerField(default=0, help_text='Quantas vezes essa chave já foi bloqueada (não zera no desbloqueio).')),
                ('primeira_falha_em', models.DateTimeField(blank=True, null=True)),
                ('ultima_falha_em', models.DateTimeField(blank=True, null=True)),
                ('desbloqueado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('desbloqueado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desbloqueios_realizados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios_login', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bloqueio de Login',
                'verbose_name_plural': 'Bloqueios de Login',
                'ordering': ['-bloqueado_ate', '-ultima_falha_em'],
                'indexes': [models.Index(fields=['tipo', 'bloqueado_ate'], name='seguranca_b_tipo_02ea87_idx')],
                'unique_together': {('tipo', 'chave')},
            },
        ),
        migrations.CreateModel(
            name='EventoSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sql_injection', 'SQL Injection'), ('path_traversal', 'Path Traversal'), ('xss', 'Cross-Site Scripting')], max_length=20)),
                ('assinatura', models.CharField(help_text='Nome da regra que casou (ex.: union_select).', max_length=60)),
                ('origem', models.CharField(choices=[('querystring', 'Query string'), ('post', 'Corpo do POST'), ('path', 'Caminho da URL'), ('header', 'Cabeçalho')], default='querystring', max_length=20)),
                ('campo', models.CharField(blank=True, default='', max_length=120)),
                ('payload', models.TextField(blank=True, default='', help_text='Trecho suspeito, truncado.')),
                ('caminho', models.CharField(blank=True, default='', max_length=500)),
                ('metodo', models.CharField(blank=True, default='', max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('bloqueado', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_seguranca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Segurança',
                'verbose_name_plural': 'Eventos de Segurança',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['-criado_em'], name='seguranca_e_criado__c1a349_idx'), models.Index(fields=['tipo', '-criado_em'], name='seguranca_e_tipo_93f71e_idx'), models.Index(fields=['ip', '-criado_em'], name='seguranca_e_ip_fec9c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='TentativaLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('sucesso', models.BooleanField(default=False)),
                ('motivo', models.CharField(choices=[('sucesso', 'Login realizado'), ('senha_invalida', 'Senha inválida'), ('usuario_inexistente', 'Usuário inexistente'), ('usuario_inativo', 'Usuário inativo'), ('2fa_invalido', 'Código 2FA inválido'), ('bloqueado', 'Tentativa com conta/IP bloqueado'), ('captcha_falhou', 'Captcha falhou')], max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Preenchido só quando o username existe de fato.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tentativas_login', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentativa de Login',
                'verbose_name_plural': 'Tentativas de Login',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['-criado_em'], name='seguranca_t_criado__a93889_idx'), models.Index(fields=['username', '-criado_em'], name='seguranca_t_usernam_a8c849_idx'), models.Index(fields=['ip', '-criado_em'], name='seguranca_t_ip_cd73bd_idx'), models.Index(fields=['sucesso', '-criado_em'], name='seguranca_t_sucesso_5b48f2_idx')],
            },
        ),
    ]
