# Generated by Django 5.2.7 on 2026-07-23 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('acessos', 'Acessos'), ('backups', 'Backups'), ('vpn', 'VPN'), ('topologia', 'Topologia'), ('tuneis', 'Túneis SSH'), ('documentos', 'Documentos'), ('rpki_irr', 'RPKI/IRR'), ('monitoramento', 'Monitoramento'), ('documentacao', 'Documentação de Rede'), ('hotspot', 'Hotspot'), ('testes_rede', 'Testes de Rede')], max_length=30)),
                ('habilitado', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Módulo do Usuário',
                'verbose_name_plural': 'Módulos do Usuário',
                'unique_together': {('usuario', 'modulo')},
            },
        ),
    ]
