# Generated by Django 5.2.7 on 2026-08-02 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instancias_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instância',
                'verbose_name_plural': 'Instâncias',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('consultor', 'Consultor'), ('operador', 'Operador')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_criados', to=settings.AUTH_USER_MODEL)),
                ('instancia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='usuario.instancia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuário',
            },
        ),
        migrations.CreateModel(
            name='InstanciaFerramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ferramenta', models.CharField(choices=[('acessos', 'Acessos'), ('backups', 'Backups'), ('vpn', 'VPN'), ('topologia', 'Topologia'), ('tuneis', 'Túneis SSH'), ('documentos', 'Documentos'), ('rpki_irr', 'RPKI/IRR'), ('monitoramento', 'Monitoramento'), ('hotspot', 'Hotspot'), ('ipam', 'IPAM'), ('scripts', 'Scripts'), ('bgp', 'BGP'), ('testes_rede', 'Testes de Rede')], max_length=30)),
                ('habilitado', models.BooleanField(default=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferramentas', to='usuario.instancia')),
            ],
            options={
                'verbose_name': 'Ferramenta da Instância',
                'verbose_name_plural': 'Ferramentas da Instância',
                'unique_together': {('instancia', 'ferramenta')},
            },
        ),
    ]
