# Generated by Django 5.2.7 on 2026-08-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_instancia_perfilusuario_instanciaferramenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanciaferramenta',
            name='ferramenta',
            field=models.CharField(choices=[('acessos', 'Acessos'), ('backups', 'Backups'), ('vpn', 'VPN'), ('topologia', 'Topologia'), ('tuneis', 'Túneis SSH'), ('documentos', 'Documentos'), ('rpki_irr', 'RPKI/IRR'), ('monitoramento', 'Monitoramento'), ('hotspot', 'Hotspot'), ('ipam', 'IPAM'), ('scripts', 'Scripts'), ('bgp', 'BGP'), ('testes_rede', 'Testes de Rede'), ('lg', 'Pesquisa LG'), ('geoip', 'Geolocalização IP'), ('firmware', 'Firmware')], max_length=30),
        ),
    ]
