# Generated by Django 5.2.7 on 2026-08-10 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_totpdevice_totpbackupcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalUsuarioInstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_portal_criados', to=settings.AUTH_USER_MODEL)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_portal', to='usuario.instancia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_instancia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instância do Usuário de Portal',
                'verbose_name_plural': 'Instâncias de Usuários de Portal',
            },
        ),
    ]
