# Generated by Django 5.2.7 on 2026-08-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_dispositivoconfiavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanciaferramenta',
            name='ferramenta',
            field=models.CharField(choices=[('acessos', 'Acessos'), ('backups', 'Backups'), ('vpn', 'VPN'), ('topologia', 'Topologia'), ('tuneis', 'Túneis SSH'), ('documentos', 'Documentos'), ('rpki_irr', 'RPKI/IRR'), ('monitoramento', 'Monitoramento'), ('hotspot', 'Hotspot'), ('ipam', 'IPAM'), ('scripts', 'Scripts'), ('bgp', 'BGP'), ('testes_rede', 'Testes de Rede'), ('lg', 'Pesquisa LG'), ('geoip', 'Geolocalização IP'), ('firmware', 'Firmware'), ('wiki', 'Wiki'), ('tarefas', 'Tarefas')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usuariomodulo',
            name='modulo',
            field=models.CharField(choices=[('acessos', 'Acessos'), ('backups', 'Backups'), ('vpn', 'VPN'), ('topologia', 'Topologia'), ('tuneis', 'Túneis SSH'), ('documentos', 'Documentos'), ('rpki_irr', 'RPKI/IRR'), ('monitoramento', 'Monitoramento'), ('documentacao', 'Documentação de Rede'), ('hotspot', 'Hotspot'), ('testes_rede', 'Testes de Rede'), ('tarefas', 'Tarefas')], max_length=30),
        ),
    ]
