# Generated by Django 5.2.7 on 2026-08-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_alter_instanciaferramenta_ferramenta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancia',
            name='principal',
            field=models.BooleanField(default=False, help_text='Marca a operação própria do Administrador (não uma revenda). Só ela tem acesso aos módulos exclusivos da plataforma — hoje, o Atendimento. Deve existir no máximo uma.', verbose_name='Instância principal'),
        ),
    ]
