# Generated by Django 5.2.7 on 2026-08-31 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0111_topologiadiagrama_pai_alter_acesso_protocolo_and_more'),
        ('usuario', '0011_marcar_instancia_principal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_permitidos', to='clientes.acesso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_permitidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Host liberado para o Usuário',
                'verbose_name_plural': 'Hosts liberados para o Usuário',
                'unique_together': {('usuario', 'acesso')},
            },
        ),
    ]
