# Generated by Django 5.2.7 on 2026-08-31 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcao_equipamento', '0002_alter_funcao_equipamento_descricao'),
        ('usuario', '0012_usuarioacesso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_permitidos', to='funcao_equipamento.funcao_equipamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcoes_permitidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Função liberada para o Usuário',
                'verbose_name_plural': 'Funções liberadas para o Usuário',
                'unique_together': {('usuario', 'funcao')},
            },
        ),
    ]
