# Generated by Django 5.2.7 on 2025-10-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo_equipamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo_equipamento',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
