# Generated by Django 5.2.7 on 2025-12-07 17:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0030_alter_backuptemplate_fabricante_blocoip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_nome', models.CharField(max_length=255)),
                ('empresa_cnpj', models.CharField(max_length=18)),
                ('empresa_logo', models.ImageField(help_text='Logo para boleto (recomendado 300x100px)', upload_to='financeiro/logos/')),
                ('banco_nome', models.CharField(help_text='Ex: Banco do Brasil', max_length=100)),
                ('banco_codigo', models.CharField(help_text='Código do banco', max_length=10)),
                ('agencia', models.CharField(max_length=10)),
                ('conta', models.CharField(max_length=20)),
                ('digito_conta', models.CharField(blank=True, max_length=1)),
                ('nosso_numero_sequencia', models.IntegerField(default=1, help_text='Próximo número sequencial')),
                ('endereco', models.TextField()),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('juros_atraso_percentual', models.DecimalField(decimal_places=2, default=0.1, help_text='Juros diário por atraso (ex: 0.10 = 0.1%)', max_digits=5)),
                ('multa_atraso', models.DecimalField(decimal_places=2, default=0, help_text='Multa fixa por atraso', max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Financeira',
                'verbose_name_plural': 'Configurações Financeiras',
            },
        ),
        migrations.CreateModel(
            name='AluguelIPv4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco_descricao', models.CharField(help_text='Ex: 200.100.50.0/24', max_length=100)),
                ('quantidade_ips', models.IntegerField(help_text='Quantidade de IPs no bloco')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('PAUSADO', 'Pausado'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('quitado', models.BooleanField(default=False)),
                ('data_quitacao', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('bloco_ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.blocoip')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alugueis_ipv4', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Aluguel IPv4',
                'verbose_name_plural': 'Alugueis IPv4',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Consultoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Ex: Consultoria de Redes', max_length=255)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_meses', models.IntegerField(default=1, help_text='Duração em meses')),
                ('periodicidade', models.CharField(choices=[('MENSAL', 'Mensal'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual'), ('UNICA', 'Única')], default='MENSAL', max_length=20)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('PAUSADO', 'Pausado'), ('CANCELADO', 'Cancelado'), ('ENCERRADO', 'Encerrado')], default='ATIVO', max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('quitado', models.BooleanField(default=False)),
                ('data_quitacao', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultorias', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Consultoria',
                'verbose_name_plural': 'Consultorias',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_fatura', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('CONSULTORIA', 'Consultoria'), ('ALUGUEL_IPV4', 'Aluguel IPv4'), ('MISTA', 'Mista (Consultoria + IPv4)')], max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ABERTA', 'Aberta'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('alugueis_ipv4', models.ManyToManyField(blank=True, related_name='faturas', to='financeiro.aluguelipv4')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='clientes.cliente')),
                ('consultorias', models.ManyToManyField(blank=True, related_name='faturas', to='financeiro.consultoria')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_boleto', models.CharField(max_length=50, unique=True)),
                ('nosso_numero', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('FATURA', 'Fatura'), ('CONSULTORIA', 'Consultoria'), ('ALUGUEL_IPV4', 'Aluguel IPv4')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_geracao', models.DateField(auto_now_add=True)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('GERADO', 'Gerado'), ('ENVIADO', 'Enviado'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='GERADO', max_length=20)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='financeiro/boletos/%Y/%m/')),
                ('codigo_barras', models.CharField(blank=True, max_length=50)),
                ('url_banco', models.URLField(blank=True, help_text='Link para pagar no banco', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='clientes.cliente')),
                ('fatura', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boleto', to='financeiro.fatura')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'ordering': ['-data_geracao'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_recibo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('BOLETO', 'Boleto'), ('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferência'), ('CARTAO', 'Cartão'), ('CHEQUE', 'Cheque'), ('OUTRO', 'Outro')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_pagamento', models.DateField()),
                ('data_confirmacao', models.DateField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, help_text='Ex: nº do comprovante', max_length=100)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='financeiro/comprovantes/%Y/%m/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('boleto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to='financeiro.boleto')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='financeiro.fatura')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_consultorias', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_alugueis', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_faturas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pago', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_aberto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('faturas_abertas', models.IntegerField(default=0)),
                ('faturas_vencidas', models.IntegerField(default=0)),
                ('faturas_pagas', models.IntegerField(default=0)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio_financeiro', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Relatório Financeiro',
                'verbose_name_plural': 'Relatórios Financeiros',
            },
        ),
    ]
