# Generated by Django 5.2.7 on 2025-12-08 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0030_alter_backuptemplate_fabricante_blocoip_and_more'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Nome do equipamento', max_length=255)),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total da venda', max_digits=12)),
                ('quantidade_parcelas', models.IntegerField(default=1, help_text='Número de parcelas')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('CANCELADO', 'Cancelado'), ('ENCERRADO', 'Encerrado')], default='ATIVO', max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('quitado', models.BooleanField(default=False)),
                ('data_quitacao', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas_equipamentos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Venda de Equipamento',
                'verbose_name_plural': 'Vendas de Equipamentos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
