# Generated by Django 5.2.7 on 2025-12-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_vendaequipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='comprovante_pdf_gerado',
            field=models.FileField(blank=True, help_text='PDF gerado automaticamente pelo sistema', null=True, upload_to='financeiro/comprovantes-pdf/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='comprovante',
            field=models.FileField(blank=True, help_text='Comprovante enviado pelo usuário (opcional: PDF, JPG, PNG)', null=True, upload_to='financeiro/comprovantes/%Y/%m/'),
        ),
    ]
