# Generated by Django 5.2.7 on 2026-05-31 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_pagamento_comprovante_pdf_gerado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', models.CharField(choices=[('INFRAESTRUTURA', 'Infraestrutura'), ('PESSOAL', 'Pessoal'), ('SERVICOS', 'Serviços'), ('ADMINISTRATIVO', 'Administrativo'), ('FISCAL', 'Fiscal / Tributário'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20)),
                ('recorrencia', models.CharField(choices=[('UNICA', 'Única'), ('MENSAL', 'Mensal'), ('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='UNICA', max_length=20)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', max_length=20)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['data_vencimento'],
            },
        ),
    ]
