# Generated by Django 5.2.7 on 2026-05-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='meses_recorrencia',
            field=models.PositiveIntegerField(blank=True, help_text='Total de meses/ocorrências da recorrência. Vazio = indefinido.', null=True),
        ),
        migrations.AddField(
            model_name='despesa',
            name='ocorrencia_atual',
            field=models.PositiveIntegerField(default=1, help_text='Número da ocorrência atual'),
        ),
    ]
