# Generated by Django 5.2.7 on 2026-06-11 17:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_configuracaofinanceira_assinatura_locador'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='asn_proprio',
            field=models.CharField(blank=True, default='', help_text='ASN da empresa locadora. Ex: AS268024. Usado na Carta LOA.', max_length=20),
        ),
        migrations.CreateModel(
            name='CartaLOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pendente', 'Aguardando assinatura'), ('assinado', 'Assinado'), ('expirado', 'Expirado')], default='pendente', max_length=20)),
                ('asn_upstream', models.CharField(blank=True, default='', help_text='ASN da locadora para trânsito BGP. Ex: AS268024', max_length=30)),
                ('assinatura_img', models.TextField(blank=True, default='')),
                ('nome_assinante', models.CharField(blank=True, default='', max_length=255)),
                ('ip_assinante', models.GenericIPAddressField(blank=True, null=True)),
                ('assinado_em', models.DateTimeField(blank=True, null=True)),
                ('pdf_assinado', models.FileField(blank=True, null=True, upload_to='loa/assinadas/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('aluguel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas_loa', to='financeiro.aluguelipv4')),
            ],
            options={
                'verbose_name': 'Carta LOA',
                'verbose_name_plural': 'Cartas LOA',
                'ordering': ['-criado_em'],
            },
        ),
    ]
