# Generated by Django 5.2.7 on 2026-06-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0014_carta_loa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaloa',
            name='responsavel_whois',
            field=models.CharField(blank=True, default='', help_text='Nome do responsável técnico encontrado via WHOIS. Pré-preenche a assinatura.', max_length=255),
        ),
    ]
