# Generated by Django 5.2.7 on 2026-06-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0015_loa_responsavel_whois'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaloa',
            name='proprietaria_whois',
            field=models.CharField(blank=True, default='', help_text='Nome do proprietário do bloco (registrant WHOIS). Aparece como assinante da LOA.', max_length=255),
        ),
        migrations.AlterField(
            model_name='cartaloa',
            name='responsavel_whois',
            field=models.CharField(blank=True, default='', help_text='Nome do contato técnico WHOIS. Pré-preenche o campo de assinatura.', max_length=255),
        ),
    ]
