# Generated by Django 5.2.7 on 2026-06-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0016_loa_proprietaria_whois'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='wa_api_key',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='API Key'),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='wa_ativo',
            field=models.BooleanField(default=False, verbose_name='Alertas WhatsApp ativos'),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='wa_dias_antes',
            field=models.IntegerField(default=3, verbose_name='Alertar X dias antes do vencimento'),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='wa_evolution_url',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='URL Evolution API'),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='wa_hora_envio',
            field=models.CharField(default='09:00', max_length=5, verbose_name='Hora de envio (HH:MM)'),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='wa_instance',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nome da Instância'),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='wa_msg_aviso',
            field=models.TextField(blank=True, default='', help_text='Variáveis: {nome}, {numero}, {valor}, {vencimento}, {dias}, {empresa}', verbose_name='Mensagem de aviso (antes do vencimento)'),
        ),
        migrations.AddField(
            model_name='configuracaofinanceira',
            name='wa_msg_vencido',
            field=models.TextField(blank=True, default='', help_text='Variáveis: {nome}, {numero}, {valor}, {vencimento}, {atraso}, {empresa}', verbose_name='Mensagem de cobrança (após vencimento)'),
        ),
    ]
