# Generated by Django 5.2.7 on 2026-06-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0018_pix_cobranca'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='vendas_equipamentos',
            field=models.ManyToManyField(blank=True, related_name='faturas', to='financeiro.vendaequipamento'),
        ),
    ]
