# Generated by Django 5.2.7 on 2025-10-06 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('host', models.GenericIPAddressField()),
                ('porta', models.PositiveIntegerField()),
                ('protocolo', models.CharField(choices=[('HTTP', 'HTTP'), ('HTTPS', 'HTTPS'), ('TELNET', 'Telnet'), ('SSH', 'SSH'), ('WINBOX', 'Winbox'), ('FTP', 'FTP'), ('FTPS', 'FTPS')], max_length=10)),
                ('usuario', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='clientes.cliente')),
            ],
        ),
    ]
