# Generated by Django 5.2.7 on 2025-10-06 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('funcao_equipamento', '0001_initial'),
        ('modelo_equipamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acesso',
            name='funcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcao_equipamento.funcao_equipamento'),
        ),
        migrations.AddField(
            model_name='acesso',
            name='host_ipv6',
            field=models.GenericIPAddressField(default='2001:db8::1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acesso',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelo_equipamento.modelo_equipamento'),
        ),
    ]
