# Generated by Django 5.2.7 on 2025-10-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='acesso',
            name='vlan',
            field=models.IntegerField(blank=True, default=100),
            preserve_default=False,
        ),
    ]
