# Generated by Django 5.2.7 on 2025-10-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_acesso_vlan'),
    ]

    operations = [
        migrations.AddField(
            model_name='acesso',
            name='senha_adm',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
