# Generated by Django 5.2.7 on 2025-10-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_acesso_senha_adm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='host_ipv6',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
