# Generated by Django 5.2.7 on 2025-10-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_acesso_host_ipv6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='tipo',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
