# Generated by Django 5.2.7 on 2025-10-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_acesso_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='tipo',
            field=models.CharField(max_length=250),
        ),
    ]
