# Generated by Django 5.2.7 on 2025-10-19 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoVPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='vpn/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_vpn', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemTopologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='topologia/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_topologia', to='clientes.cliente')),
            ],
        ),
    ]
