# Generated by Django 5.2.7 on 2025-10-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_arquivovpn_imagemtopologia'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivovpn',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arquivovpn',
            name='senha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='arquivovpn',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
