# Generated by Django 5.2.7 on 2025-10-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_categoria_chamado_comentariochamado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='host',
            field=models.CharField(max_length=255),
        ),
    ]
