# Generated by Django 5.2.7 on 2025-10-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_alter_acesso_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='vlan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
