# Generated by Django 5.2.7 on 2025-10-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_alter_acesso_vlan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome_empresa',
            field=models.CharField(max_length=255),
        ),
    ]
