# Generated by Django 5.2.7 on 2025-10-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_alter_cliente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='acesso',
            name='winbox',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
