# Generated by Django 5.2.7 on 2025-10-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0018_acesso_winbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='winbox',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
