# Generated by Django 5.2.7 on 2025-10-24 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_proxyserver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxyserver',
            options={'ordering': ['-ativo', 'nome'], 'verbose_name': 'Servidor Proxy', 'verbose_name_plural': 'Servidores Proxy'},
        ),
        migrations.AddField(
            model_name='proxyserver',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proxies', to='clientes.cliente'),
            preserve_default=False,
        ),
    ]
