# Generated by Django 5.2.7 on 2025-10-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0021_alter_proxyserver_options_proxyserver_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='porta',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
