# Generated by Django 5.2.7 on 2025-10-29 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0023_templatebackup_agendamentobackup_backupequipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='acesso',
            name='template_backup',
            field=models.ForeignKey(blank=True, help_text='Template Ansible para backup deste equipamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos', to='clientes.templatebackup'),
        ),
    ]
