# Generated by Django 5.2.7 on 2025-10-31 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0024_acesso_template_backup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupequipamento',
            name='acesso',
        ),
        migrations.RemoveField(
            model_name='backupequipamento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='backupequipamento',
            name='executado_por',
        ),
        migrations.RemoveField(
            model_name='backupequipamento',
            name='template',
        ),
        migrations.RemoveField(
            model_name='acesso',
            name='template_backup',
        ),
        migrations.DeleteModel(
            name='AgendamentoBackup',
        ),
        migrations.DeleteModel(
            name='BackupEquipamento',
        ),
        migrations.DeleteModel(
            name='TemplateBackup',
        ),
    ]
