# Generated by Django 5.2.7 on 2025-11-06 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0025_remove_backupequipamento_acesso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(choices=[('HUAWEI', 'Huawei'), ('JUNIPER', 'Juniper'), ('CISCO', 'Cisco'), ('MIKROTIK', 'MikroTik')], max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('playbook_path', models.CharField(help_text='Caminho do playbook: /path/to/backup_huawei.yml', max_length=255)),
                ('backup_path', models.CharField(default='/mnt/backups/', help_text='Diretório onde os backups serão salvos', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de Backup',
                'verbose_name_plural': 'Templates de Backup',
                'ordering': ['fabricante'],
            },
        ),
        migrations.AddField(
            model_name='acesso',
            name='template_backup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos', to='clientes.backuptemplate'),
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='backups/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('EXECUTANDO', 'Executando'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=20)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('log_execucao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_execucao', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('tamanho_arquivo', models.BigIntegerField(default=0, help_text='Tamanho em bytes')),
                ('acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='clientes.acesso')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='clientes.backuptemplate')),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['acesso', '-data_criacao'], name='clientes_ba_acesso__c13dfb_idx'), models.Index(fields=['status', '-data_criacao'], name='clientes_ba_status_135c68_idx')],
            },
        ),
    ]
