# Generated by Django 5.2.7 on 2025-11-06 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0026_backuptemplate_acesso_template_backup_backup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acesso',
            name='template_backup',
        ),
        migrations.DeleteModel(
            name='Backup',
        ),
        migrations.DeleteModel(
            name='BackupTemplate',
        ),
    ]
