# Generated by Django 5.2.7 on 2025-11-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0028_backuptemplate_acesso_backup_automatico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuptemplate',
            name='fabricante',
            field=models.CharField(choices=[('CISCO', 'Cisco'), ('HUAWEI', 'Huawei'), ('MIKROTIK', 'MikroTik'), ('JUNIPER', 'Juniper'), ('DELL', 'Dell'), ('HP', 'HP/Aruba'), ('EXTREME', 'Extreme Networks'), ('GENERICO', 'Genérico'), ('DATACOM', 'Datacom')], max_length=20),
        ),
    ]
