# Generated by Django 5.2.7 on 2025-11-29 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0029_alter_backuptemplate_fabricante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuptemplate',
            name='fabricante',
            field=models.CharField(choices=[('CISCO', 'Cisco'), ('HUAWEI', 'Huawei'), ('MIKROTIK', 'MikroTik'), ('JUNIPER', 'Juniper'), ('DELL', 'Dell'), ('HP', 'HP/Aruba'), ('EXTREME', 'Extreme Networks'), ('GENERICO', 'Genérico')], max_length=20),
        ),
        migrations.CreateModel(
            name='BlocoIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IPV4', 'IPv4'), ('IPV6', 'IPv6')], max_length=4)),
                ('bloco', models.CharField(help_text='Ex: 200.100.50.0/24 ou 2801:80:1234::/48', max_length=100)),
                ('asn', models.CharField(blank=True, help_text='Ex: AS12345', max_length=20, null=True)),
                ('irr_registry', models.CharField(blank=True, help_text='Ex: LACNIC, RIPE, ARIN', max_length=50, null=True)),
                ('rpki_valido', models.BooleanField(default=False)),
                ('irr_valido', models.BooleanField(default=False)),
                ('ultima_validacao', models.DateTimeField(blank=True, null=True)),
                ('rpki_status', models.CharField(blank=True, max_length=20, null=True)),
                ('rpki_mensagem', models.TextField(blank=True, null=True)),
                ('irr_status', models.CharField(blank=True, max_length=20, null=True)),
                ('irr_mensagem', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos_ip', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Bloco de IP',
                'verbose_name_plural': 'Blocos de IP',
                'ordering': ['cliente', 'tipo', 'bloco'],
            },
        ),
        migrations.CreateModel(
            name='ValidacaoRPKI_IRR_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_validacao', models.DateTimeField(auto_now_add=True)),
                ('rpki_valido', models.BooleanField(default=False)),
                ('rpki_status', models.CharField(blank=True, max_length=20, null=True)),
                ('rpki_detalhes', models.TextField(blank=True, null=True)),
                ('irr_valido', models.BooleanField(default=False)),
                ('irr_status', models.CharField(blank=True, max_length=20, null=True)),
                ('irr_detalhes', models.TextField(blank=True, null=True)),
                ('duracao_segundos', models.FloatField(default=0)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_validacao', to='clientes.blocoip')),
            ],
            options={
                'verbose_name': 'Log de Validação RPKI/IRR',
                'verbose_name_plural': 'Logs de Validação RPKI/IRR',
                'ordering': ['-data_validacao'],
            },
        ),
    ]
