# Generated by Django 5.2.7 on 2025-12-15 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0030_alter_backuptemplate_fabricante_blocoip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopologiaDiagrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('xml_conteudo', models.TextField(help_text='Conteúdo XML do Draw.io')),
                ('versao', models.IntegerField(default=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativa', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topologias_diagramas', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Topologia Diagrama',
                'verbose_name_plural': 'Topologias Diagramas',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='TopologiaMapeamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento_id', models.CharField(help_text='ID do elemento no Draw.io', max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.acesso')),
                ('topologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeamentos', to='clientes.topologiadiagrama')),
            ],
            options={
                'verbose_name': 'Mapeamento Topologia',
                'verbose_name_plural': 'Mapeamentos Topologia',
                'unique_together': {('topologia', 'acesso')},
            },
        ),
    ]
