# Generated by Django 5.2.7 on 2025-12-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0031_topologiadiagrama_topologiamapeamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topologiamapeamento',
            name='topologia',
        ),
        migrations.AlterUniqueTogether(
            name='topologiamapeamento',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='topologiamapeamento',
            name='acesso',
        ),
        migrations.DeleteModel(
            name='TopologiaDiagrama',
        ),
        migrations.DeleteModel(
            name='TopologiaMapeamento',
        ),
    ]
