# Generated by Django 5.2.7 on 2025-12-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0031_topologiadiagrama_topologiamapeamento'),
    ]

    operations = [
        # AlterUniqueTogether tem que vir ANTES dos RemoveField: o
        # unique_together de 0031 é ('topologia', 'acesso') e o Django
        # resolve os nomes das colunas pelo estado do modelo na hora de
        # derrubar o índice. Removendo o campo primeiro, a criação do banco
        # de teste quebrava com "TopologiaMapeamento has no field named
        # 'topologia'" — nenhum teste do projeto conseguia rodar do zero.
        migrations.AlterUniqueTogether(
            name='topologiamapeamento',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='topologiamapeamento',
            name='topologia',
        ),
        migrations.RemoveField(
            model_name='topologiamapeamento',
            name='acesso',
        ),
        migrations.DeleteModel(
            name='TopologiaDiagrama',
        ),
        migrations.DeleteModel(
            name='TopologiaMapeamento',
        ),
    ]
