# Generated by Django 5.2.7 on 2025-12-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0032_remove_topologiamapeamento_topologia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemtopologia',
            name='drawio_url',
            field=models.URLField(blank=True, help_text='URL da topologia editável no DrawIO (ex: draw.io/...)', null=True, verbose_name='Link DrawIO'),
        ),
    ]
