# Generated by Django 5.2.7 on 2025-12-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0033_imagemtopologia_drawio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemtopologia',
            name='arquivo_drawio',
            field=models.FileField(blank=True, help_text='Arquivo .drawio para edição e sincronização', null=True, upload_to='topologia/drawio/', verbose_name='Arquivo DrawIO'),
        ),
        migrations.AddField(
            model_name='imagemtopologia',
            name='ultima_atualizacao_drawio',
            field=models.DateTimeField(auto_now=True, verbose_name='Última atualização DrawIO'),
        ),
        migrations.AlterField(
            model_name='imagemtopologia',
            name='drawio_url',
            field=models.URLField(blank=True, help_text='Se usar DrawIO Cloud, cole o link aqui', null=True, verbose_name='Link DrawIO Cloud'),
        ),
    ]
