# Generated by Django 5.2.7 on 2025-12-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0034_imagemtopologia_arquivo_drawio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemtopologia',
            name='arquivo_drawio',
            field=models.FileField(blank=True, null=True, upload_to='topologia/drawio/', verbose_name='Arquivo DrawIO'),
        ),
        migrations.AlterField(
            model_name='imagemtopologia',
            name='drawio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagemtopologia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='topologia/'),
        ),
        migrations.AlterField(
            model_name='imagemtopologia',
            name='ultima_atualizacao_drawio',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
