# Generated by Django 5.2.7 on 2025-12-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0035_alter_imagemtopologia_arquivo_drawio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemtopologia',
            name='arquivo_drawio',
        ),
        migrations.RemoveField(
            model_name='imagemtopologia',
            name='drawio_url',
        ),
        migrations.RemoveField(
            model_name='imagemtopologia',
            name='ultima_atualizacao_drawio',
        ),
        migrations.AlterField(
            model_name='imagemtopologia',
            name='imagem',
            field=models.ImageField(upload_to='topologia/'),
        ),
    ]
