# Generated by Django 5.2.7 on 2026-03-08 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0038_comentarioacesso'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentacaoRedeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phpipam_habilitado', models.BooleanField(default=False)),
                ('phpipam_url', models.CharField(blank=True, help_text='Ex: http://192.168.1.10/phpipam', max_length=500, null=True)),
                ('phpipam_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('phpipam_senha', models.CharField(blank=True, max_length=200, null=True)),
                ('netbox_habilitado', models.BooleanField(default=False)),
                ('netbox_url', models.CharField(blank=True, help_text='Ex: http://192.168.1.20:8000', max_length=500, null=True)),
                ('netbox_token', models.CharField(blank=True, help_text='Token de API do NetBox (opcional)', max_length=200, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentacao_config', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Configuração de Documentação de Rede',
                'verbose_name_plural': 'Configurações de Documentação de Rede',
            },
        ),
    ]
