# Generated by Django 5.2.7 on 2026-05-09 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0039_documentacaoredeconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopologiaDiagrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Nova Topologia', max_length=255)),
                ('dados_json', models.TextField(default='{"nodes":[],"links":[]}', verbose_name='Dados do editor')),
                ('drawio_xml', models.TextField(blank=True, default='', verbose_name='XML draw.io')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagramas_topologia', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
