# Generated by Django 5.2.7 on 2026-05-14 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0040_topologia_diagrama'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPNServidorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor_public_key', models.CharField(max_length=200)),
                ('servidor_private_key', models.CharField(max_length=200)),
                ('servidor_endpoint', models.CharField(help_text='IP ou hostname público do servidor', max_length=200)),
                ('servidor_porta', models.IntegerField(default=51820)),
                ('interface_criada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuração Servidor VPN',
            },
        ),
        migrations.CreateModel(
            name='VPNWireGuard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='VPN MikroTik', max_length=100)),
                ('cliente_private_key', models.CharField(max_length=200)),
                ('cliente_public_key', models.CharField(max_length=200)),
                ('preshared_key', models.CharField(blank=True, max_length=200)),
                ('vpn_ip', models.GenericIPAddressField(unique=True)),
                ('redes_privadas', models.TextField(blank=True, help_text='Uma rede por linha, ex: 192.168.1.0/24')),
                ('ativo', models.BooleanField(default=True)),
                ('peer_no_servidor', models.BooleanField(default=False, help_text='Peer adicionado ao wg0')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpns_wg', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'VPN WireGuard',
                'verbose_name_plural': 'VPNs WireGuard',
                'ordering': ['-criado_em'],
            },
        ),
    ]
