# Generated by Django 5.2.7 on 2026-05-14 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0041_vpn_wireguard'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAMPrefixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('container', 'Container'), ('rede', 'Rede'), ('pool', 'Pool')], default='rede', max_length=15)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('reservado', 'Reservado'), ('deprecado', 'Deprecado')], default='ativo', max_length=15)),
                ('descricao', models.TextField(blank=True)),
                ('local', models.CharField(blank=True, max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipam_prefixos', to='clientes.cliente')),
            ],
            options={
                'ordering': ['prefixo'],
            },
        ),
        migrations.CreateModel(
            name='IPAMSubRede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rede', models.CharField(max_length=50)),
                ('gateway', models.CharField(blank=True, max_length=45)),
                ('descricao', models.TextField(blank=True)),
                ('local', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('reservado', 'Reservado'), ('deprecado', 'Deprecado')], default='ativo', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipam_subredes', to='clientes.cliente')),
                ('prefixo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subredes', to='clientes.ipamprefixo')),
            ],
            options={
                'ordering': ['rede'],
            },
        ),
        migrations.CreateModel(
            name='IPAMEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=45)),
                ('tipo', models.CharField(choices=[('fixo', 'Fixo'), ('dhcp', 'DHCP'), ('reservado', 'Reservado'), ('gateway', 'Gateway'), ('rede', 'Endereço de Rede'), ('broadcast', 'Broadcast')], default='fixo', max_length=15)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('reservado', 'Reservado')], default='ativo', max_length=15)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('mac_address', models.CharField(blank=True, max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('acesso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipam_enderecos', to='clientes.acesso')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipam_ips', to='clientes.cliente')),
                ('subrede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ips', to='clientes.ipamsubrede')),
            ],
            options={
                'ordering': ['ip'],
            },
        ),
        migrations.CreateModel(
            name='IPAMVlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('reservado', 'Reservado'), ('deprecado', 'Deprecado')], default='ativo', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipam_vlans', to='clientes.cliente')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('cliente', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='ipamsubrede',
            name='vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subredes', to='clientes.ipamvlan'),
        ),
        migrations.CreateModel(
            name='IPAMVpnDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('ipsec', 'IPSec'), ('gre', 'GRE'), ('l2tp', 'L2TP'), ('mpls', 'MPLS/L3VPN'), ('wireguard', 'WireGuard'), ('openvpn', 'OpenVPN'), ('outro', 'Outro')], default='ipsec', max_length=15)),
                ('endpoint_local', models.CharField(blank=True, max_length=100)),
                ('endpoint_remoto', models.CharField(blank=True, max_length=100)),
                ('rede_local', models.CharField(blank=True, max_length=200)),
                ('rede_remota', models.CharField(blank=True, max_length=200)),
                ('as_local', models.CharField(blank=True, max_length=20)),
                ('as_remoto', models.CharField(blank=True, max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipam_vpns', to='clientes.cliente')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
