# Generated by Django 5.2.7 on 2026-05-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0042_ipam_nativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipamprefixo',
            name='pool_cheia',
            field=models.BooleanField(default=False),
        ),
    ]
