# Generated by Django 5.2.7 on 2026-05-15 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0043_ipamprefixo_pool_cheia'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenVPNConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vpn', models.CharField(max_length=60)),
                ('ip_publico', models.CharField(max_length=45)),
                ('porta', models.IntegerField(default=61194)),
                ('ros_version', models.CharField(choices=[('6', 'v6'), ('7', 'v7')], default='7', max_length=2)),
                ('vpn_pool', models.CharField(default='192.168.250.128-192.168.250.254', max_length=100)),
                ('vpn_local_ip', models.CharField(default='192.168.250.1', max_length=45)),
                ('vpn_username', models.CharField(max_length=100)),
                ('vpn_password', models.CharField(max_length=100)),
                ('cert_passphrase', models.CharField(max_length=100)),
                ('rate_limit', models.CharField(default='50M/50M', max_length=50)),
                ('ovpn_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('configurando', 'Configurando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='configurando', max_length=20)),
                ('logs', models.TextField(blank=True)),
                ('erro_msg', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('acesso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openvpn_configs', to='clientes.acesso')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openvpn_configs', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
