# Generated by Django 5.2.7 on 2026-05-15 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0044_openvpnconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenVPNUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('ovpn_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('configurando', 'Configurando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='configurando', max_length=20)),
                ('logs', models.TextField(blank=True)),
                ('erro_msg', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='clientes.openvpnconfig')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
