# Generated by Django 5.2.7 on 2026-05-16 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0045_openvpn_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRRConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn', models.CharField(help_text='Número do AS sem prefixo. Ex: 272418', max_length=20)),
                ('as_name', models.CharField(help_text='Nome curto do AS. Ex: INFORLIMA', max_length=100)),
                ('empresa_descr', models.CharField(help_text='Descrição completa. Ex: INFORLIMA TELECOM', max_length=200)),
                ('nic_hdl', models.CharField(help_text='Handle NIC. Ex: JOLJE19-NICBR', max_length=80)),
                ('irr_password', models.CharField(help_text='Senha plaintext enviada no e-mail IRR', max_length=200)),
                ('auth_bcrypt', models.CharField(blank=True, help_text='Hash BCRYPT-PW do mntner', max_length=400)),
                ('email_contato', models.EmailField(help_text='E-mail do responsável técnico (changed, upd-to, notify)', max_length=254)),
                ('email_abuse', models.EmailField(blank=True, help_text='E-mail de abuse/rede (remarks)', max_length=254)),
                ('website', models.CharField(blank=True, max_length=300)),
                ('person_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('ipv4_rotas', models.JSONField(blank=True, default=list, help_text='Lista de prefixos IPv4. Ex: ["186.65.76.0/22"]')),
                ('ipv6_rotas', models.JSONField(blank=True, default=list, help_text='Lista de prefixos IPv6. Ex: ["2804:80E0::/32"]')),
                ('route_set_members', models.JSONField(blank=True, default=list, help_text='mp-members do route-set com range. Ex: ["201.7.168.0/21^21-24"]')),
                ('upstream_asns', models.JSONField(blank=True, default=list, help_text='Lista [{"asn":"AS52554","nome":"MEGASNET"}]')),
                ('customer_asns', models.JSONField(blank=True, default=list, help_text='Lista [{"asn":"AS268024","nome":""}]')),
                ('geo_pais', models.CharField(default='BR', max_length=5)),
                ('geo_pais_alpha3', models.CharField(default='BRA', max_length=5)),
                ('geo_pais_num', models.CharField(default='076', max_length=5)),
                ('geo_estado', models.CharField(blank=True, max_length=20)),
                ('geo_cidade', models.CharField(blank=True, max_length=100)),
                ('smtp_host', models.CharField(blank=True, max_length=200)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, max_length=200)),
                ('smtp_pass', models.CharField(blank=True, max_length=200)),
                ('smtp_from', models.EmailField(blank=True, help_text='Endereço de origem do e-mail. Se vazio usa email_contato.', max_length=254)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='irr_config', to='clientes.cliente')),
            ],
        ),
    ]
