# Generated by Django 5.2.7 on 2026-05-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0046_irr_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, max_length=200, verbose_name='Host SMTP')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='Porta SMTP')),
                ('smtp_user', models.CharField(blank=True, max_length=200, verbose_name='Usuário SMTP')),
                ('smtp_pass', models.CharField(blank=True, max_length=200, verbose_name='Senha SMTP')),
                ('smtp_from', models.EmailField(blank=True, max_length=254, verbose_name='E-mail Remetente')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Usar TLS (STARTTLS)')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
            },
        ),
        migrations.RemoveField(
            model_name='irrconfig',
            name='smtp_from',
        ),
        migrations.RemoveField(
            model_name='irrconfig',
            name='smtp_host',
        ),
        migrations.RemoveField(
            model_name='irrconfig',
            name='smtp_pass',
        ),
        migrations.RemoveField(
            model_name='irrconfig',
            name='smtp_port',
        ),
        migrations.RemoveField(
            model_name='irrconfig',
            name='smtp_user',
        ),
    ]
