# Generated by Django 5.2.7 on 2026-05-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0047_config_sistema_irr'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrconfig',
            name='ix_members',
            field=models.JSONField(blank=True, default=list, help_text='Lista de member-of (IX). Ex: ["AS-PTTMetro-SP","AS65001:AS-ANNOUNCEMENTS"]'),
        ),
    ]
