# Generated by Django 5.2.7 on 2026-05-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0048_add_ix_members_to_irrconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='imap_host',
            field=models.CharField(blank=True, max_length=200, verbose_name='Host IMAP'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='imap_port',
            field=models.IntegerField(default=993, verbose_name='Porta IMAP'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='imap_use_ssl',
            field=models.BooleanField(default=True, verbose_name='Usar SSL (IMAP)'),
        ),
    ]
