# Generated by Django 5.2.7 on 2026-05-17 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0050_firmware_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrecaoGeoIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(db_index=True, max_length=50, verbose_name='Prefixo / IP')),
                ('pais', models.CharField(blank=True, max_length=5, verbose_name='País (ISO)')),
                ('regiao', models.CharField(blank=True, max_length=100, verbose_name='Estado / Região')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('org', models.CharField(blank=True, max_length=200, verbose_name='Organização / ISP')),
                ('lat', models.CharField(blank=True, max_length=20, verbose_name='Latitude')),
                ('lon', models.CharField(blank=True, max_length=20, verbose_name='Longitude')),
                ('destinos_email', models.JSONField(default=list, verbose_name='Destinos (e-mail)')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de envio')),
                ('resposta_recebida', models.BooleanField(default=False, verbose_name='Resposta recebida')),
                ('resposta_remetente', models.CharField(blank=True, max_length=200, verbose_name='Remetente da resposta')),
                ('resposta_assunto', models.CharField(blank=True, max_length=300, verbose_name='Assunto da resposta')),
                ('resposta_texto', models.TextField(blank=True, verbose_name='Corpo da resposta')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data da resposta')),
                ('aplicado', models.BooleanField(blank=True, null=True, verbose_name='Correção aplicada')),
                ('ultima_verificacao', models.DateTimeField(blank=True, null=True, verbose_name='Última verificação')),
                ('resultado_verificacao', models.JSONField(blank=True, null=True, verbose_name='Resultado da verificação')),
                ('fontes_aplicadas', models.IntegerField(default=0, verbose_name='Fontes que aplicaram')),
                ('fontes_total', models.IntegerField(default=0, verbose_name='Total de fontes verificadas')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcoes_geoip', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Correção GeoIP',
                'verbose_name_plural': 'Correções GeoIP',
                'ordering': ['-data_envio'],
            },
        ),
    ]
