# Generated by Django 5.2.7 on 2026-05-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0053_scriptcrm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptcrm',
            name='comandos',
            field=models.TextField(help_text='Um comando por linha. Use {PARAM} para variáveis. Suporte a #FOR i FROM {X} TO {Y} ... #ENDFOR', verbose_name='Comandos'),
        ),
        migrations.AlterField(
            model_name='scriptcrm',
            name='parametros',
            field=models.JSONField(default=list, help_text='Lista de parâmetros: [{nome, label, tipo, default, obrigatorio, ajuda, opcoes}]', verbose_name='Parâmetros'),
        ),
    ]
