# Generated by Django 5.2.7 on 2026-05-18 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0055_zte_auto_prov_script'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claude_api_key', models.CharField(blank=True, max_length=300, verbose_name='API Key Claude')),
                ('claude_model', models.CharField(default='claude-sonnet-4-6', max_length=100, verbose_name='Modelo Claude')),
                ('claude_max_tokens', models.IntegerField(default=4096, verbose_name='Max Tokens')),
                ('claude_temperature', models.FloatField(default=0.2, verbose_name='Temperature')),
                ('aprovacao_padrao', models.BooleanField(default=True, verbose_name='Exigir aprovação para comandos de escrita')),
                ('timeout_sessao_wa', models.IntegerField(default=120, verbose_name='Timeout sessão WhatsApp (min)')),
                ('prefixo_wa', models.CharField(default='@noc', max_length=20, verbose_name='Prefixo de invocação WA')),
                ('max_comandos_sessao', models.IntegerField(default=50, verbose_name='Máx. comandos por sessão')),
                ('wa_grupo_noc', models.CharField(blank=True, max_length=150, verbose_name='JID grupo NOC interno (escalonamento)')),
                ('wa_noc_numero', models.CharField(blank=True, max_length=30, verbose_name='Número plantão NOC (escalonamento)')),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Agent NOC',
            },
        ),
        migrations.CreateModel(
            name='EvolutionAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='URL da API')),
                ('api_key', models.CharField(blank=True, max_length=300, verbose_name='API Key')),
                ('instance_name', models.CharField(blank=True, max_length=100, verbose_name='Nome da Instância')),
                ('webhook_secret', models.CharField(blank=True, max_length=300, verbose_name='Webhook Secret')),
                ('conectado', models.BooleanField(default=False, verbose_name='Conectado')),
                ('numero_wa', models.CharField(blank=True, max_length=30, verbose_name='Número WhatsApp conectado')),
                ('ultima_sync', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Evolution API',
            },
        ),
        migrations.AlterField(
            model_name='scriptcrm',
            name='modo_execucao',
            field=models.CharField(choices=[('operacional', 'Operacional (show/get)'), ('configuracao', 'Configuração (config)'), ('zte_auto_prov', 'ZTE — Auto-Provisionamento em Massa')], default='operacional', max_length=20, verbose_name='Modo'),
        ),
        migrations.CreateModel(
            name='AgentKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo (Markdown)')),
                ('categoria', models.CharField(choices=[('comando', 'Referência de Comandos'), ('procedure', 'Procedimento Operacional'), ('troubleshooting', 'Troubleshooting'), ('topologia', 'Topologia / Infraestrutura'), ('equipamento', 'Equipamento / Modelo'), ('alarme', 'Interpretação de Alarme'), ('geral', 'Geral')], default='geral', max_length=30, verbose_name='Categoria')),
                ('fabricante', models.CharField(choices=[('zte', 'ZTE'), ('huawei', 'Huawei'), ('cisco', 'Cisco'), ('mikrotik', 'MikroTik'), ('datacom', 'Datacom'), ('parks', 'Parks'), ('generico', 'Genérico')], default='generico', max_length=30, verbose_name='Fabricante')),
                ('tags', models.JSONField(default=list, help_text='Ex: ["onu","gpon","los"]', verbose_name='Tags')),
                ('ativo', models.BooleanField(default=True)),
                ('uso_count', models.IntegerField(default=0, verbose_name='Vezes consultado pelo agent')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Vazio = conhecimento global disponível para todos', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_knowledge', to='clientes.cliente', verbose_name='Cliente (específico)')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_knowledge_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Base de Conhecimento Agent',
                'verbose_name_plural': 'Base de Conhecimento Agent',
                'ordering': ['-uso_count', 'fabricante', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.CharField(max_length=150, unique=True, verbose_name='JID (ID WhatsApp)')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('grupo', 'Grupo'), ('contato', 'Contato individual')], default='grupo', max_length=10, verbose_name='Tipo')),
                ('foto_url', models.URLField(blank=True, verbose_name='URL da foto')),
                ('nivel_permissao', models.CharField(choices=[('leitura', 'Leitura — apenas show/display/get'), ('operacional', 'Operacional — comandos pré-aprovados'), ('admin', 'Admin — aprovação inline via WA')], default='leitura', max_length=20, verbose_name='Nível de permissão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('sincronizado_em', models.DateTimeField(auto_now=True, verbose_name='Última sincronização')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Grupo só poderá acessar hosts deste cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_grupos', to='clientes.cliente', verbose_name='Cliente vinculado')),
                ('hosts_permitidos', models.ManyToManyField(blank=True, help_text='Vazio = todos os hosts do cliente vinculado', related_name='wa_grupos_permitidos', to='clientes.acesso', verbose_name='Hosts permitidos')),
            ],
            options={
                'verbose_name': 'Grupo/Contato WhatsApp',
                'verbose_name_plural': 'Grupos/Contatos WhatsApp',
                'ordering': ['nome'],
            },
        ),
    ]
