# Generated by Django 5.2.7 on 2026-05-19 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0056_agent_noc_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('terminal', 'Terminal Web')], max_length=20, verbose_name='Canal')),
                ('canal_id', models.CharField(blank=True, max_length=200, verbose_name='ID do canal (JID ou session key)')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('encerrada', 'Encerrada'), ('expirada', 'Expirada')], default='ativa', max_length=20)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_atividade', models.DateTimeField(auto_now=True)),
                ('acesso_ativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sessoes', to='clientes.acesso', verbose_name='Host ativo na sessão')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sessoes', to='clientes.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sessoes', to=settings.AUTH_USER_MODEL)),
                ('wa_grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes', to='clientes.whatsappgrupo', verbose_name='Grupo WhatsApp')),
            ],
            options={
                'verbose_name': 'Sessão Agent NOC',
                'verbose_name_plural': 'Sessões Agent NOC',
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('user_msg', 'Mensagem do usuário'), ('agent_msg', 'Resposta do agent'), ('tool_call', 'Chamada de ferramenta'), ('tool_result', 'Resultado de ferramenta'), ('error', 'Erro'), ('system', 'Evento de sistema')], max_length=20, verbose_name='Tipo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('tool_name', models.CharField(blank=True, max_length=100, verbose_name='Ferramenta')),
                ('tool_input', models.JSONField(blank=True, null=True, verbose_name='Input da ferramenta')),
                ('tool_output', models.TextField(blank=True, verbose_name='Output da ferramenta')),
                ('tokens_input', models.IntegerField(default=0, verbose_name='Tokens entrada')),
                ('tokens_output', models.IntegerField(default=0, verbose_name='Tokens saída')),
                ('duracao_ms', models.IntegerField(default=0, verbose_name='Duração (ms)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='clientes.agentsessao', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Log Agent NOC',
                'verbose_name_plural': 'Logs Agent NOC',
                'ordering': ['criado_em'],
            },
        ),
    ]
