# Generated by Django 5.2.7 on 2026-05-19 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0057_agent_sessao_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentKnowledgeDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('arquivo', models.FileField(upload_to='agent_docs/', verbose_name='Arquivo PDF')),
                ('nome_arquivo', models.CharField(blank=True, max_length=255)),
                ('tamanho_kb', models.PositiveIntegerField(default=0)),
                ('paginas', models.PositiveIntegerField(default=0)),
                ('conteudo_extraido', models.TextField(blank=True, verbose_name='Texto extraído do PDF')),
                ('categoria', models.CharField(choices=[('comando', 'Referência de Comandos'), ('procedure', 'Procedimento Operacional'), ('troubleshooting', 'Troubleshooting'), ('topologia', 'Topologia / Infraestrutura'), ('equipamento', 'Equipamento / Modelo'), ('alarme', 'Interpretação de Alarme'), ('geral', 'Geral')], default='geral', max_length=30, verbose_name='Categoria')),
                ('fabricante', models.CharField(choices=[('zte', 'ZTE'), ('huawei', 'Huawei'), ('cisco', 'Cisco'), ('mikrotik', 'MikroTik'), ('datacom', 'Datacom'), ('parks', 'Parks'), ('generico', 'Genérico')], default='generico', max_length=30, verbose_name='Fabricante')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('ativo', models.BooleanField(default=True)),
                ('uso_count', models.IntegerField(default=0, verbose_name='Vezes consultado pelo agent')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Vazio = disponível para todos', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_docs', to='clientes.cliente', verbose_name='Cliente (específico)')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_docs_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento PDF — Agent',
                'verbose_name_plural': 'Documentos PDF — Agent',
                'ordering': ['-uso_count', 'fabricante', 'titulo'],
            },
        ),
    ]
