# Generated by Django 5.2.7 on 2026-05-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0058_agent_knowledge_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=300, verbose_name='API Key OpenAI'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='openai_max_tokens',
            field=models.IntegerField(default=4096, verbose_name='Max Tokens OpenAI'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='openai_model',
            field=models.CharField(default='gpt-4o', max_length=100, verbose_name='Modelo OpenAI'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='openai_temperature',
            field=models.FloatField(default=0.2, verbose_name='Temperature OpenAI'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='provedor_ia',
            field=models.CharField(choices=[('claude', 'Claude (Anthropic)'), ('openai', 'ChatGPT (OpenAI)')], default='claude', max_length=20, verbose_name='Provedor de IA'),
        ),
    ]
