# Generated by Django 5.2.7 on 2026-05-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0062_ipamsubrede_pool_cheia'),
    ]

    operations = [
        migrations.AddField(
            model_name='acesso',
            name='contexto_backup',
            field=models.TextField(blank=True, default='', help_text='Resumo de interfaces, IPs e VLANs extraído do último backup — usado pelo Agent NOC', verbose_name='Contexto do Backup (Agent NOC)'),
        ),
        migrations.AddField(
            model_name='acesso',
            name='contexto_backup_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Contexto atualizado em'),
        ),
    ]
