# Generated by Django 5.2.7 on 2026-05-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0065_trocasenhajob'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnwireguard',
            name='interface_nome',
            field=models.CharField(blank=True, default='wg0', help_text='Interface WireGuard (ex: wg1, wg2). wg0=legado compartilhado', max_length=20),
        ),
        migrations.AddField(
            model_name='vpnwireguard',
            name='servidor_ip_local',
            field=models.CharField(blank=True, default='', help_text='IP do servidor nesta interface (ex: 10.201.0.1). Usado como source-bind para routing isolado.', max_length=45),
        ),
        migrations.AlterField(
            model_name='trocasenhaacesso',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trocasenhajob',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
