# Generated by Django 5.2.7 on 2026-06-08 17:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0066_vpn_interface_isolada'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('interface', models.CharField(default='bridge', max_length=50)),
                ('network', models.CharField(default='192.168.88.0/24', max_length=18)),
                ('gateway', models.CharField(default='192.168.88.1', max_length=15)),
                ('pool_start', models.CharField(default='192.168.88.10', max_length=15)),
                ('pool_end', models.CharField(default='192.168.88.254', max_length=15)),
                ('dns_servidor', models.CharField(default='8.8.8.8', max_length=15)),
                ('session_timeout', models.IntegerField(default=0, help_text='Minutos (0=ilimitado)')),
                ('idle_timeout', models.IntegerField(default=30, help_text='Minutos')),
                ('rate_limit_down', models.CharField(default='10M', max_length=20)),
                ('rate_limit_up', models.CharField(default='5M', max_length=20)),
                ('guest_usuario', models.CharField(default='guest', max_length=50)),
                ('guest_senha', models.CharField(default='wifi123', max_length=50)),
                ('portal_titulo', models.CharField(default='WiFi Grátis', max_length=100)),
                ('portal_subtitulo', models.CharField(blank=True, max_length=200)),
                ('cor_primaria', models.CharField(default='#1a73e8', max_length=7)),
                ('configurado_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('acesso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotspot_configs', to='clientes.acesso')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_configs', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Configuração Hotspot',
                'verbose_name_plural': 'Configurações Hotspot',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HotspotBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='hotspot/banners/')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('hotspot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='clientes.hotspotconfig')),
            ],
            options={
                'verbose_name': 'Banner Hotspot',
                'verbose_name_plural': 'Banners Hotspot',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HotspotLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('mac', models.CharField(blank=True, max_length=17)),
                ('ip_cliente', models.CharField(blank=True, max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('hotspot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='clientes.hotspotconfig')),
            ],
            options={
                'verbose_name': 'Lead Hotspot',
                'verbose_name_plural': 'Leads Hotspot',
                'ordering': ['-criado_em'],
            },
        ),
    ]
