# Generated by Django 5.2.7 on 2026-06-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0067_hotspot_config_banner_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotlead',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
