# Generated by Django 5.2.7 on 2026-06-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0072_cliente_notas_acesso_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappgrupo',
            name='claude_api_key',
            field=models.CharField(blank=True, help_text='Chave Anthropic própria deste grupo/cliente — consome os créditos dele. O Agent NOC só responde neste grupo se esta chave estiver configurada.', max_length=300, verbose_name='API Key Claude do cliente'),
        ),
        migrations.AlterField(
            model_name='acesso',
            name='notas',
            field=models.TextField(blank=True, default='', help_text='Notas sobre este host para o Agent NOC (senha ADM, restrições de horário, comportamentos especiais).', verbose_name='Notas do Agent NOC'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='notas',
            field=models.TextField(blank=True, default='', help_text='Informações, peculiaridades e contexto do cliente para o Agent NOC (topologia, acordos, restrições).', verbose_name='Notas do Agent NOC'),
        ),
    ]
