# Generated by Django 5.2.7 on 2026-07-08 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0073_whatsappgrupo_claude_api_key_alter_acesso_notas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuarios_adicionais',
            field=models.ManyToManyField(blank=True, help_text='Outros usuários que também podem logar e acessar o painel deste cliente.', related_name='clientes_adicionais', to=settings.AUTH_USER_MODEL, verbose_name='Usuários adicionais'),
        ),
    ]
