# Generated by Django 5.2.7 on 2026-07-09 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_pai_prefixos(apps, schema_editor):
    """
    Popula IPAMPrefixo.pai pros registros já existentes, usando a mesma lógica
    de containment CIDR de _computar_pai_id (clientes/ipam_views.py) —
    reimplementada aqui em vez de importada, pois migrations não devem
    depender de código de app que pode mudar (usa apps.get_model, modelo
    histórico, não o real).
    """
    import ipaddress
    IPAMPrefixo = apps.get_model('clientes', 'IPAMPrefixo')

    for cliente_id in IPAMPrefixo.objects.values_list('cliente_id', flat=True).distinct():
        prefixos = list(IPAMPrefixo.objects.filter(cliente_id=cliente_id).values_list('id', 'prefixo'))
        nets = {}
        for pid, cidr in prefixos:
            try:
                nets[pid] = ipaddress.ip_network(cidr, strict=False)
            except ValueError:
                continue

        for pid, alvo_net in nets.items():
            melhor_id, melhor_pl = None, -1
            for outro_id, outro_net in nets.items():
                if outro_id == pid or outro_net.version != alvo_net.version:
                    continue
                if outro_net.prefixlen >= alvo_net.prefixlen:
                    continue
                if alvo_net.subnet_of(outro_net) and outro_net.prefixlen > melhor_pl:
                    melhor_id, melhor_pl = outro_id, outro_net.prefixlen
            if melhor_id is not None:
                IPAMPrefixo.objects.filter(id=pid).update(pai_id=melhor_id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    # Postgres não permite CREATE INDEX na mesma transação em que uma FK
    # auto-referenciada (IPAMPrefixo.pai) acabou de ser validada nessa mesma
    # tabela ("cannot CREATE INDEX because it has pending trigger events") —
    # roda cada operação em sua própria transação pra evitar o conflito.
    atomic = False

    dependencies = [
        ('clientes', '0074_cliente_usuarios_adicionais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ipamprefixo',
            name='pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos', to='clientes.ipamprefixo'),
        ),
        migrations.AddField(
            model_name='ipamsubrede',
            name='scan_automatico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipamsubrede',
            name='ultimo_scan',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IPAMAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('vlan', 'VLAN'), ('prefixo', 'Prefixo'), ('subrede', 'Sub-rede'), ('ip', 'Endereço IP'), ('vpn', 'VPN')], max_length=15)),
                ('objeto_id', models.IntegerField()),
                ('objeto_repr', models.CharField(blank=True, max_length=255)),
                ('acao', models.CharField(choices=[('created', 'Criado'), ('updated', 'Atualizado'), ('deleted', 'Removido')], max_length=10)),
                ('mudancas', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipam_audit_logs', to='clientes.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='IPAMScanResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, max_length=45)),
                ('online', models.BooleanField(default=False)),
                ('checado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipam_scan_resultados', to='clientes.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'ip')},
            },
        ),
        migrations.DeleteModel(
            name='DocumentacaoRedeConfig',
        ),
        migrations.RunPython(backfill_pai_prefixos, noop_reverse),
    ]
