# Generated by Django 5.2.7 on 2026-07-10 19:46

import clientes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0076_cliente_usuario_opcional'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPNOpenVPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='VPN MikroTik', max_length=100)),
                ('common_name', models.CharField(help_text='CN do certificado do cliente', max_length=100, unique=True)),
                ('redes_privadas', models.TextField(blank=True, default=clientes.models._ovpn_redes_padrao, help_text='Uma rede por linha, ex: 192.168.1.0/24')),
                ('vpn_ip', models.GenericIPAddressField(help_text='IP do cliente no túnel (10.90.0.x)', unique=True)),
                ('token', models.CharField(default=clientes.models._ovpn_token_default, help_text='Token do endpoint público de bootstrap — regenerar invalida o link antigo', max_length=64, unique=True)),
                ('cert_emitido', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpns_ovpn', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'VPN OpenVPN',
                'verbose_name_plural': 'VPNs OpenVPN',
                'ordering': ['-criado_em'],
            },
        ),
    ]
