# Generated by Django 5.2.7 on 2026-07-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0077_vpn_openvpn'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnopenvpn',
            name='interface_nome',
            field=models.CharField(blank=True, default='', help_text='Nome da instância/interface dedicada (ex: server-crm-1)', max_length=30),
        ),
        migrations.AddField(
            model_name='vpnopenvpn',
            name='porta',
            field=models.IntegerField(blank=True, help_text='Porta TCP dedicada desta instância (1195+N)', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vpnopenvpn',
            name='subnet_n',
            field=models.IntegerField(blank=True, help_text='N usado para compor a sub-rede dedicada 10.91.{N}.0/30', null=True),
        ),
        migrations.AlterField(
            model_name='vpnopenvpn',
            name='vpn_ip',
            field=models.GenericIPAddressField(help_text='IP do cliente no túnel (10.91.N.2)', unique=True),
        ),
    ]
