# Generated by Django 5.2.7 on 2026-07-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0078_vpn_openvpn_isolamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotconfig',
            name='cor_fundo',
            field=models.CharField(default='#0a0a0f', max_length=7),
        ),
        migrations.AddField(
            model_name='hotspotconfig',
            name='cor_secundaria',
            field=models.CharField(blank=True, default='', help_text='Cor secundária para o gradiente dos botões/fundo (opcional — usa um tom da primária se vazio)', max_length=7),
        ),
        migrations.AddField(
            model_name='hotspotconfig',
            name='estilo_fundo',
            field=models.CharField(choices=[('gradiente', 'Gradiente (padrão)'), ('solido', 'Cor sólida'), ('imagem', 'Imagem')], default='gradiente', max_length=10),
        ),
        migrations.AddField(
            model_name='hotspotconfig',
            name='imagem_fundo',
            field=models.ImageField(blank=True, null=True, upload_to='hotspot/fundos/'),
        ),
    ]
