# Generated by Django 5.2.7 on 2026-07-20 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0079_hotspotconfig_cor_fundo_hotspotconfig_cor_secundaria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ssh', 'SSH'), ('telnet', 'Telnet'), ('winbox', 'WinBox Web'), ('winbox_nativo', 'WinBox Nativo'), ('webfig', 'WebFig')], max_length=20)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('encerrada', 'Encerrada')], default='ativa', max_length=20)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
                ('arquivo_video', models.CharField(blank=True, default='', max_length=500)),
                ('acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_auditoria', to='clientes.acesso')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_acesso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de Acesso (Auditoria)',
                'verbose_name_plural': 'Sessões de Acesso (Auditoria)',
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.CreateModel(
            name='AcessoComando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comando', models.TextField()),
                ('executado_em', models.DateTimeField(auto_now_add=True)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandos', to='clientes.acessosessao')),
            ],
            options={
                'verbose_name': 'Comando de Sessão (Auditoria)',
                'verbose_name_plural': 'Comandos de Sessão (Auditoria)',
                'ordering': ['executado_em'],
            },
        ),
    ]
