# Generated by Django 5.2.7 on 2026-07-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0080_acessosessao_acessocomando'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessosessao',
            name='transcript',
            field=models.TextField(blank=True, default=''),
        ),
    ]
