# Generated by Django 5.2.7 on 2026-07-23 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0081_acessosessao_transcript'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=100)),
                ('interface_fisica', models.CharField(max_length=50)),
                ('network', models.CharField(default='192.168.89.0/24', max_length=18)),
                ('gateway', models.CharField(default='192.168.89.1', max_length=15)),
                ('pool_start', models.CharField(default='192.168.89.10', max_length=15)),
                ('pool_end', models.CharField(default='192.168.89.254', max_length=15)),
                ('dns_servidor', models.CharField(default='8.8.8.8', max_length=15)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('hotspot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='clientes.hotspotconfig')),
            ],
            options={
                'verbose_name': 'Interface Adicional — Hotspot',
                'verbose_name_plural': 'Interfaces Adicionais — Hotspot',
                'ordering': ['id'],
            },
        ),
    ]
