# Generated by Django 5.2.7 on 2026-07-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0082_hotspotinterface'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotinterface',
            name='interface',
            field=models.CharField(default='bridge', max_length=50),
        ),
        migrations.AlterField(
            model_name='hotspotinterface',
            name='interface_fisica',
            field=models.CharField(blank=True, default='', help_text='Só usada quando "Interface" = bridge', max_length=50),
        ),
    ]
