# Generated by Django 5.2.7 on 2026-07-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0083_hotspotinterface_interface_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotlead',
            name='termos_aceitos',
            field=models.BooleanField(default=False, help_text='Aceite dos Termos de Uso e Política de Privacidade no login'),
        ),
    ]
