# Generated by Django 5.2.7 on 2026-07-23 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0084_hotspotlead_termos_aceitos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('acessos', 'Acessos'), ('backups', 'Backups'), ('vpn', 'VPN'), ('topologia', 'Topologia'), ('tuneis', 'Túneis SSH'), ('documentos', 'Documentos'), ('rpki_irr', 'RPKI/IRR'), ('monitoramento', 'Monitoramento'), ('documentacao', 'Documentação de Rede'), ('hotspot', 'Hotspot'), ('testes_rede', 'Testes de Rede')], max_length=30)),
                ('habilitado', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Módulo do Cliente',
                'verbose_name_plural': 'Módulos do Cliente',
                'unique_together': {('cliente', 'modulo')},
            },
        ),
    ]
