# Generated by Django 5.2.7 on 2026-07-23 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0085_clientemodulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteIntegracaoDisparo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('chatmix', 'Chatmix'), ('opa_suit', 'Opa Suit')], max_length=20)),
                ('habilitado', models.BooleanField(default=False)),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('api_token', models.CharField(blank=True, default='', max_length=255)),
                ('template_id', models.CharField(blank=True, default='', help_text='ID do template HSM (Mensagens → Templates → número no final da URL)', max_length=20)),
                ('mensagem_modelo', models.TextField(default='Olá {nome}! Recebemos seu cadastro em nosso WiFi grátis e ficamos felizes em ter você por aqui. Em breve podemos entrar em contato pelo número {telefone}. Bem-vindo(a)!', help_text='Use {nome} e {telefone} para indicar as variáveis do lead, na ordem esperada pelo template.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integracoes_disparo', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Integração de Disparo (Cliente)',
                'verbose_name_plural': 'Integrações de Disparo (Cliente)',
                'unique_together': {('cliente', 'provider')},
            },
        ),
    ]
