# Generated by Django 5.2.7 on 2026-07-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0085_clientemodulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClienteModulo',
        ),
    ]
