# Generated by Django 5.2.7 on 2026-07-23 14:24
import re

import clientes.models
from django.db import migrations, models


def _converter_mensagem_em_variaveis(apps, schema_editor):
    """Templates HSM do Chatmix podem exigir qualquer quantidade de
    variáveis — o campo antigo (`mensagem_modelo`, um texto livre) só
    permitia inferir nome/telefone. Para configs já salvas, extrai as
    variáveis na mesma ordem em que apareciam no texto, preservando o
    que já estava configurado (o operador ainda pode ajustar a
    quantidade de variáveis depois, na tela de Integração Disparo)."""
    ClienteIntegracaoDisparo = apps.get_model('clientes', 'ClienteIntegracaoDisparo')
    placeholder_re = re.compile(r'\{(nome|telefone)\}')
    for cfg in ClienteIntegracaoDisparo.objects.all():
        ordem = placeholder_re.findall(cfg.mensagem_modelo or '')
        cfg.variaveis_modelo = ['{' + chave + '}' for chave in ordem] or ['{nome}', '{telefone}']
        cfg.save(update_fields=['variaveis_modelo'])


def _reverter_variaveis_em_mensagem(apps, schema_editor):
    ClienteIntegracaoDisparo = apps.get_model('clientes', 'ClienteIntegracaoDisparo')
    for cfg in ClienteIntegracaoDisparo.objects.all():
        cfg.mensagem_modelo = ' '.join(str(v) for v in (cfg.variaveis_modelo or []))
        cfg.save(update_fields=['mensagem_modelo'])


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0086_clienteintegracaodisparo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteintegracaodisparo',
            name='variaveis_modelo',
            field=models.JSONField(default=clientes.models._disparo_variaveis_padrao, help_text='Uma entrada por variável exigida pelo template, na mesma ordem. Use {nome}/{telefone} ou texto fixo.'),
        ),
        migrations.RunPython(_converter_mensagem_em_variaveis, _reverter_variaveis_em_mensagem),
        migrations.RemoveField(
            model_name='clienteintegracaodisparo',
            name='mensagem_modelo',
        ),
    ]
