# Generated by Django 5.2.7 on 2026-07-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0087_remove_clienteintegracaodisparo_mensagem_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteintegracaodisparo',
            name='api_dominio',
            field=models.CharField(blank=True, default='', help_text='Domínio da conta (só Opa Suite), ex: https://minhaempresa.opasuite.com.br', max_length=255),
        ),
        migrations.AddField(
            model_name='clienteintegracaodisparo',
            name='canal_id',
            field=models.CharField(blank=True, default='', help_text='ID do canal de comunicação (só Opa Suite)', max_length=64),
        ),
        migrations.AlterField(
            model_name='clienteintegracaodisparo',
            name='provider',
            field=models.CharField(choices=[('chatmix', 'Chatmix'), ('opa_suit', 'Opa Suite')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clienteintegracaodisparo',
            name='template_id',
            field=models.CharField(blank=True, default='', help_text='ID do template (Chatmix: número no final da URL do template; Opa Suite: campo _id do template)', max_length=64),
        ),
    ]
