# Generated by Django 5.2.7 on 2026-07-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0086_delete_clientemodulo'),
        ('clientes', '0088_clienteintegracaodisparo_api_dominio_and_more'),
    ]

    operations = [
    ]
