# Generated by Django 5.2.7 on 2026-07-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0089_merge_20260724_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotconfig',
            name='cor_painel',
            field=models.CharField(default='#0f0f19', help_text='Cor do painel/card de login (transparência aplicada automaticamente)', max_length=7),
        ),
    ]
