# Generated by Django 5.2.7 on 2026-07-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0090_hotspotconfig_cor_painel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotconfig',
            name='cor_texto',
            field=models.CharField(default='#ffffff', help_text='Cor das letras do formulário (título, campos, rodapé)', max_length=7),
        ),
    ]
