# Generated by Django 5.2.7 on 2026-07-26 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0091_hotspotconfig_cor_texto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofeedBloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Prefixo / Bloco IP')),
                ('pais', models.CharField(blank=True, max_length=5, verbose_name='País (ISO)')),
                ('regiao', models.CharField(blank=True, max_length=100, verbose_name='Estado / Região')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='CEP / Postal Code')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo no Geofeed')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocos_geofeed', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Bloco do Geofeed',
                'verbose_name_plural': 'Blocos do Geofeed',
                'ordering': ['prefixo'],
            },
        ),
    ]
