# Generated by Django 5.2.7 on 2026-07-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0093_geofeed_bloco_migrar_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofeedbloco',
            name='empresa',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Empresa (dona do bloco)'),
        ),
        migrations.AddField(
            model_name='geofeedbloco',
            name='empresa_slug',
            field=models.SlugField(blank=True, max_length=220, verbose_name='Slug da empresa (URL do geofeed)'),
        ),
    ]
