# Generated by Django 5.2.7 on 2026-07-31 18:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0094_geofeed_bloco_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalLinkExterno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('revogado', models.BooleanField(default=False)),
                ('acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_externos', to='clientes.acesso')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links_terminal_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Link Externo de Terminal',
                'verbose_name_plural': 'Links Externos de Terminal',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='acessosessao',
            name='link_externo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes', to='clientes.terminallinkexterno'),
        ),
    ]
