# Generated by Django 5.2.7 on 2026-07-31 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0095_terminallinkexterno_acessosessao_link_externo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoBgp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ativar_sessao', 'Ativar sessão'), ('desativar_sessao', 'Desativar sessão'), ('prepend', 'Adicionar prepend'), ('parar_anuncio', 'Parar de anunciar')], max_length=20)),
                ('alvo', models.CharField(max_length=255)),
                ('comandos', models.TextField()),
                ('output', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro')], max_length=10)),
                ('executado_em', models.DateTimeField(auto_now_add=True)),
                ('acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_bgp', to='clientes.acesso')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ação BGP (Auditoria)',
                'verbose_name_plural': 'Ações BGP (Auditoria)',
                'ordering': ['-executado_em'],
            },
        ),
        migrations.CreateModel(
            name='BgpSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(blank=True, default='', max_length=20)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('erro', models.TextField(blank=True, default='')),
                ('gerado_em', models.DateTimeField(auto_now=True)),
                ('acesso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bgp_snapshot', to='clientes.acesso')),
                ('backup_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.backuplog')),
            ],
            options={
                'verbose_name': 'Snapshot BGP',
                'verbose_name_plural': 'Snapshots BGP',
            },
        ),
    ]
