# Generated by Django 5.2.7 on 2026-08-01 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0096_acaobgp_bgpsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='acaobgp',
            name='tipo',
            field=models.CharField(choices=[('ativar_sessao', 'Ativar sessão'), ('desativar_sessao', 'Desativar sessão'), ('prepend', 'Adicionar prepend'), ('parar_anuncio', 'Parar de anunciar'), ('community', 'Aplicar community'), ('novo_anuncio', 'Anunciar prefixo novo')], max_length=20),
        ),
        migrations.CreateModel(
            name='BgpCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessao_nome', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bgp_communities', to='clientes.acesso')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community BGP (por sessão)',
                'verbose_name_plural': 'Communities BGP (por sessão)',
                'ordering': ['sessao_nome', 'label'],
                'unique_together': {('acesso', 'sessao_nome', 'label')},
            },
        ),
    ]
