# Generated by Django 5.2.7 on 2026-08-02 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0097_alter_acaobgp_tipo_bgpcommunity'),
        ('usuario', '0002_instancia_perfilusuario_instanciaferramenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='instancia',
            field=models.ForeignKey(blank=True, help_text='Consultor dono deste cliente. Vazio = cliente da plataforma (só o Administrador vê).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='usuario.instancia', verbose_name='Instância'),
        ),
    ]
