# Generated by Django 5.2.7 on 2026-08-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0098_cliente_instancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgpsnapshot',
            name='patch_local_pendente',
            field=models.BooleanField(default=False),
        ),
    ]
