# Generated by Django 5.2.7 on 2026-08-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0100_mikrotik_backup_show_sensitive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acaobgp',
            name='tipo',
            field=models.CharField(choices=[('ativar_sessao', 'Ativar sessão'), ('desativar_sessao', 'Desativar sessão'), ('prepend', 'Adicionar prepend'), ('parar_anuncio', 'Parar de anunciar'), ('community', 'Aplicar community'), ('novo_anuncio', 'Anunciar prefixo novo'), ('criar_sessao', 'Criar sessão nova')], max_length=20),
        ),
    ]
