# Generated by Django 5.2.7 on 2026-08-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0101_alter_acaobgp_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrconfig',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key do mntner migrado (opcional) — gerada na interface web do TC, usada como alternativa/complemento à senha na API', max_length=200),
        ),
        migrations.AlterField(
            model_name='irrconfig',
            name='irr_password',
            field=models.CharField(help_text='Senha do mntner — usada tanto no objeto RPSL quanto na autenticação da API (campo passwords)', max_length=200),
        ),
    ]
