# Generated by Django 5.2.7 on 2026-08-10 11:21

from django.db import migrations, models


def _converter_rotas_para_dict(apps, schema_editor):
    """Converte itens legados (string = apenas prefixo) para o novo formato
    dict {"prefix","descr","member_of"}, mantendo descr/member_of vazios
    (caem no padrão global na geração do RPSL)."""
    IRRConfig = apps.get_model('clientes', 'IRRConfig')
    for cfg in IRRConfig.objects.all():
        mudou = False
        for campo in ('ipv4_rotas', 'ipv6_rotas'):
            lista = getattr(cfg, campo) or []
            nova = []
            for item in lista:
                if isinstance(item, str):
                    nova.append({'prefix': item, 'descr': '', 'member_of': ''})
                    mudou = True
                else:
                    nova.append(item)
            if mudou:
                setattr(cfg, campo, nova)
        if mudou:
            cfg.save(update_fields=['ipv4_rotas', 'ipv6_rotas'])


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0102_irrconfig_add_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrconfig',
            name='ipv4_rotas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de rotas IPv4. Ex: [{"prefix":"186.65.76.0/22","descr":"ANTONIO CLAUDIO","member_of":"AS271699:RS-GOODNET-NORTE"}]'),
        ),
        migrations.AlterField(
            model_name='irrconfig',
            name='ipv6_rotas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de rotas IPv6. Ex: [{"prefix":"2804:80E0::/32","descr":"ANTONIO CLAUDIO","member_of":"AS271699:RS-GOODNET-NORTE"}]'),
        ),
        migrations.RunPython(_converter_rotas_para_dict, migrations.RunPython.noop),
    ]
