# Generated by Django 5.2.7 on 2026-08-10 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0103_irr_rotas_com_descr_member_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmpScanExecucaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('total_ips', models.PositiveIntegerField(default=0)),
                ('total_probes', models.PositiveIntegerField(default=0)),
                ('total_vulneraveis', models.PositiveIntegerField(default=0)),
                ('total_protegidos', models.PositiveIntegerField(default=0)),
                ('blocos_ignorados', models.PositiveIntegerField(default=0, help_text='Blocos fora do limite de tamanho suportado (IPv4 < /16 ou IPv6 < /112)')),
                ('sucesso', models.BooleanField(default=True)),
                ('erro_mensagem', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ampscan_execucoes', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Execução AmpScan',
                'verbose_name_plural': 'Execuções AmpScan',
                'ordering': ['-iniciado_em'],
            },
        ),
        migrations.CreateModel(
            name='AmpScanResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, max_length=45)),
                ('porta', models.PositiveIntegerField()),
                ('protocolo', models.CharField(help_text='udp ou tcp', max_length=4)),
                ('servico', models.CharField(help_text='Ex: DNS, NTP, SNMP, MEMCACHED', max_length=50)),
                ('descricao_risco', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('vulneravel', 'Vulnerável'), ('protegido', 'Protegido (aberto, mitigado)')], default='vulneravel', max_length=12)),
                ('tempo_resposta_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('primeira_deteccao', models.DateTimeField(auto_now_add=True)),
                ('ultima_deteccao', models.DateTimeField(auto_now=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('bloco_ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ampscan_resultados', to='clientes.blocoip')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ampscan_resultados', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Resultado AmpScan',
                'verbose_name_plural': 'Resultados AmpScan',
                'ordering': ['-ultima_deteccao'],
                'unique_together': {('cliente', 'ip', 'porta', 'protocolo')},
            },
        ),
    ]
