# Generated by Django 5.2.7 on 2026-08-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0104_ampscanexecucaolog_ampscanresultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ampscanexecucaolog',
            name='total_expostos',
            field=models.PositiveIntegerField(default=0, help_text='Portas de gestão remota (SSH/RDP) abertas — não conta como vulnerabilidade'),
        ),
        migrations.AlterField(
            model_name='ampscanresultado',
            name='status',
            field=models.CharField(choices=[('vulneravel', 'Vulnerável'), ('protegido', 'Protegido (aberto, mitigado)'), ('exposto', 'Exposto (gestão remota)')], default='vulneravel', max_length=12),
        ),
    ]
