# Generated by Django 5.2.7 on 2026-08-11 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0105_ampscanexecucaolog_total_expostos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotaLoopExecucaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('total_blocos_testados', models.PositiveIntegerField(default=0)),
                ('total_loops_detectados', models.PositiveIntegerField(default=0)),
                ('sucesso', models.BooleanField(default=True)),
                ('erro_mensagem', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotaloop_execucoes', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Execução de Teste de Loop de Roteamento',
                'verbose_name_plural': 'Execuções de Teste de Loop de Roteamento',
                'ordering': ['-iniciado_em'],
            },
        ),
        migrations.CreateModel(
            name='RotaLoopResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_alvo', models.CharField(max_length=45)),
                ('status', models.CharField(choices=[('loop_detectado', 'Loop detectado')], default='loop_detectado', max_length=15)),
                ('ip_em_loop', models.CharField(max_length=45)),
                ('hops', models.JSONField(blank=True, default=list, help_text='Lista [{"hop": int, "ip": str|None}, ...]')),
                ('ferramenta', models.CharField(default='mtr', max_length=10)),
                ('primeira_deteccao', models.DateTimeField(auto_now_add=True)),
                ('ultima_deteccao', models.DateTimeField(auto_now=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('bloco_ip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rotaloop_resultado', to='clientes.blocoip')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotaloop_resultados', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Resultado de Loop de Roteamento',
                'verbose_name_plural': 'Resultados de Loop de Roteamento',
                'ordering': ['-ultima_deteccao'],
            },
        ),
    ]
