# Generated by Django 5.2.7 on 2026-08-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0106_rotaloopexecucaolog_rotaloopresultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acaobgp',
            name='tipo',
            field=models.CharField(choices=[('ativar_sessao', 'Ativar sessão'), ('desativar_sessao', 'Desativar sessão'), ('prepend', 'Adicionar prepend'), ('parar_anuncio', 'Parar de anunciar'), ('community', 'Aplicar community'), ('novo_anuncio', 'Anunciar prefixo novo'), ('criar_sessao', 'Criar sessão nova'), ('anuncio_community', 'Definir anúncio por community'), ('novo_prefixo_community', 'Originar prefixo novo (community)'), ('provisionar_circuito', 'Gerar config de circuito')], max_length=30),
        ),
    ]
