# Generated by Django 5.2.7 on 2026-08-13 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0107_alter_acaobgp_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoL2vpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(blank=True, default='', max_length=255, verbose_name='Serviço de origem (clonado de)')),
                ('alvo', models.CharField(max_length=255)),
                ('servico_id', models.CharField(blank=True, default='', max_length=32, verbose_name='ID do serviço (vsi-id/pw-id/vc-id)')),
                ('vendor', models.CharField(blank=True, default='', max_length=20)),
                ('comandos', models.TextField()),
                ('output', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro')], max_length=10)),
                ('executado_em', models.DateTimeField(auto_now_add=True)),
                ('acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_l2vpn', to='clientes.acesso')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ação L2VPN (Auditoria)',
                'verbose_name_plural': 'Ações L2VPN (Auditoria)',
                'ordering': ['-executado_em'],
            },
        ),
    ]
