# Generated by Django 5.2.7 on 2026-08-14 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0108_acao_l2vpn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoOltPon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('info', 'Informações da porta'), ('state', 'Estado da porta'), ('laser_off', 'Desligar laser'), ('laser_on', 'Ligar laser')], max_length=20)),
                ('slot', models.CharField(max_length=16, verbose_name='Placa (frame/slot)')),
                ('portas', models.CharField(blank=True, default='', max_length=64, verbose_name='Portas alvo (separadas por vírgula)')),
                ('onts_afetadas', models.IntegerField(default=0, verbose_name='ONTs nas portas no momento da ação')),
                ('escrita', models.BooleanField(default=False, verbose_name='Alterou o equipamento (laser on/off)')),
                ('comandos', models.TextField()),
                ('output', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro')], max_length=10)),
                ('executado_em', models.DateTimeField(auto_now_add=True)),
                ('acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_olt_pon', to='clientes.acesso')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ação PON na OLT (Auditoria)',
                'verbose_name_plural': 'Ações PON na OLT (Auditoria)',
                'ordering': ['-executado_em'],
            },
        ),
    ]
