# Generated by Django 5.2.7 on 2026-08-19 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0110_corrige_status_acao_olt_pon'),
    ]

    operations = [
        migrations.AddField(
            model_name='topologiadiagrama',
            name='pai',
            field=models.ForeignKey(blank=True, help_text='Se preenchido, este diagrama é um sub-mapa aberto a partir de um nó do mapa pai.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submapas', to='clientes.topologiadiagrama', verbose_name='Mapa pai'),
        ),
        migrations.AlterField(
            model_name='acesso',
            name='protocolo',
            field=models.CharField(choices=[('HTTP', 'HTTP'), ('HTTPS', 'HTTPS'), ('TELNET', 'Telnet'), ('SSH', 'SSH'), ('WINBOX', 'Winbox'), ('FTP', 'FTP'), ('FTPS', 'FTPS'), ('RDP', 'RDP')], max_length=10),
        ),
        migrations.AlterField(
            model_name='acessosessao',
            name='tipo',
            field=models.CharField(choices=[('ssh', 'SSH'), ('telnet', 'Telnet'), ('winbox', 'WinBox Web'), ('winbox_nativo', 'WinBox Nativo'), ('webfig', 'WebFig'), ('rdp', 'RDP Web')], max_length=20),
        ),
    ]
