# Generated by Django 5.2.7 on 2026-08-14 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0111_topologiadiagrama_pai_alter_acesso_protocolo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VPNServidorConfig',
        ),
        migrations.DeleteModel(
            name='VPNWireGuard',
        ),
    ]
