# Generated by Django 5.2.7 on 2026-09-11 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0114_openvpnconfig_profile_existente'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(choices=[('SSH', 'SSH'), ('TELNET', 'TELNET'), ('HTTP', 'HTTP'), ('HTTPS', 'HTTPS'), ('RDP', 'RDP')], max_length=10)),
                ('porta', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocolos_extras', to='clientes.acesso')),
            ],
            options={
                'verbose_name': 'Protocolo extra de acesso',
                'verbose_name_plural': 'Protocolos extras de acesso',
                'ordering': ['id'],
                'unique_together': {('acesso', 'protocolo', 'porta')},
            },
        ),
    ]
