# Generated by Django 5.2.7 on 2026-09-19 15:13

import clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0115_acessoprotocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgpsnapshot',
            name='dados',
            field=models.JSONField(blank=True, default=dict, encoder=clientes.models.JsonUtf8Encoder),
        ),
    ]
