# Generated by Django 5.2.7 on 2026-09-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0116_alter_bgpsnapshot_dados'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='janela_continuacao_wa',
            field=models.IntegerField(default=5, help_text='Depois de chamado com o prefixo, por quantos minutos o agent segue respondendo no mesmo grupo sem precisar ser mencionado de novo. 0 = exige o prefixo em toda mensagem.', verbose_name='Janela de continuação sem menção (min)'),
        ),
    ]
