# Generated by Django 5.2.7 on 2026-09-17 12:20

import django.db.models.deletion
import projeto_rede.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0115_acessoprotocolo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoRede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('asis', 'AS-IS da infraestrutura'), ('change_plan', 'Change Plan TO-BE')], default='asis', max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('versao', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('revisao', 'Em revisão'), ('fechado', 'Fechado tecnicamente'), ('apresentado', 'Apresentado ao cliente')], default='rascunho', max_length=20)),
                ('metadados', projeto_rede.models.JSONTextoField(blank=True, default=dict)),
                ('secoes', projeto_rede.models.JSONTextoField(blank=True, default=list)),
                ('coleta', projeto_rede.models.JSONTextoField(blank=True, default=dict, help_text='Resumo das fontes usadas na geração (backups, hashes, datas).')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_rede', to='clientes.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('documento_base', models.ForeignKey(blank=True, help_text='AS-IS de origem de um Change Plan TO-BE.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivados', to='projeto_rede.documentorede')),
            ],
            options={
                'verbose_name': 'Documento de rede',
                'verbose_name_plural': 'Documentos de rede',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoRedeRevisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(max_length=20)),
                ('status', models.CharField(blank=True, default='', max_length=20)),
                ('metadados', projeto_rede.models.JSONTextoField(blank=True, default=dict)),
                ('secoes', projeto_rede.models.JSONTextoField(blank=True, default=list)),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='projeto_rede.documentorede')),
            ],
            options={
                'verbose_name': 'Revisão de documento de rede',
                'verbose_name_plural': 'Revisões de documentos de rede',
                'ordering': ['-criado_em'],
            },
        ),
    ]
