# Generated by Django 5.2.7 on 2026-09-17 13:50

import django.db.models.deletion
import projeto_rede.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0115_acessoprotocolo'),
        ('projeto_rede', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentorede',
            name='dados',
            field=projeto_rede.models.JSONTextoField(blank=True, default=dict, help_text='Conteúdo estruturado (convenção do HLD, referências e mapeamentos do TO-BE).'),
        ),
        migrations.AlterField(
            model_name='documentorede',
            name='tipo',
            field=models.CharField(choices=[('hld', 'HLD — Arquitetura de rede'), ('asis', 'AS-IS da infraestrutura'), ('change_plan', 'Change Plan TO-BE')], default='asis', max_length=20),
        ),
        migrations.CreateModel(
            name='CenarioTopologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Cenário TO-BE', max_length=255)),
                ('dados_json', models.TextField(default='{"nodes":[],"links":[]}')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cenarios_topologia', to='clientes.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clientes.topologiadiagrama', verbose_name='Mapa de origem')),
            ],
            options={
                'verbose_name': 'Cenário de topologia TO-BE',
                'verbose_name_plural': 'Cenários de topologia TO-BE',
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
