# Generated by Django 5.2.7 on 2026-06-01 18:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0066_vpn_interface_isolada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('evolution_url', models.URLField()),
                ('api_key', models.CharField(max_length=500)),
                ('instance_name', models.CharField(max_length=255)),
                ('business_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('webhook_configured', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conexão WhatsApp',
                'verbose_name_plural': 'Conexões WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'Online'), ('busy', 'Ocupado'), ('away', 'Ausente'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('is_group', models.BooleanField(default=True)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('members_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('archived', 'Arquivado'), ('deleted', 'Deletado')], default='active', max_length=20)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='atendimento.whatsappconnection')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('conversation_id', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('new', 'Novo'), ('open', 'Aberto'), ('pending', 'Aguardando'), ('resolved', 'Resolvido'), ('closed', 'Fechado')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='atendimento.contactgroup')),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('opened', 'Aberto'), ('assigned', 'Atribuído'), ('status_changed', 'Status alterado'), ('note_added', 'Nota adicionada'), ('message_sent', 'Mensagem enviada'), ('closed', 'Fechado')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='atendimento.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('conversations', models.ManyToManyField(blank=True, related_name='tags', to='atendimento.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('customer', 'Cliente'), ('agent', 'Atendente'), ('system', 'Sistema')], max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('document', 'Documento'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('location', 'Localização'), ('system', 'Sistema')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('external_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('attachment_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='atendimento.conversation')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('model', models.CharField(default='claude-3.5-sonnet', max_length=100)),
                ('system_prompt', models.TextField()),
                ('auto_respond', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_config', to='atendimento.whatsappconnection')),
            ],
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status', '-last_message_at'], name='atendimento_status_2dd0e0_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['assigned_to', 'status'], name='atendimento_assigne_5c500c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['group', 'status'], name='atendimento_group_i_812320_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationactivity',
            index=models.Index(fields=['conversation', '-created_at'], name='atendimento_convers_5f5ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='atendimento_convers_a8cbb2_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['external_id'], name='atendimento_externa_5429cd_idx'),
        ),
        migrations.AddIndex(
            model_name='contactgroup',
            index=models.Index(fields=['connection', 'status'], name='atendimento_connect_cce264_idx'),
        ),
        migrations.AddIndex(
            model_name='contactgroup',
            index=models.Index(fields=['cliente'], name='atendimento_cliente_cd9809_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contactgroup',
            unique_together={('jid', 'connection')},
        ),
    ]
