# Generated by Django 5.2.7 on 2026-06-01 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#7c3aed', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChatFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('greeting_message', models.TextField()),
                ('subject_question', models.TextField(default='Qual é o assunto do seu chamado?')),
                ('category_question', models.TextField(default='Qual categoria melhor descreve o problema?')),
                ('categories', models.JSONField(default=list)),
                ('group_ids', models.JSONField(default=list)),
                ('completion_message', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fluxo de Auto Atendimento',
                'verbose_name_plural': 'Fluxos de Auto Atendimento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KanbanBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quadro Kanban',
                'verbose_name_plural': 'Quadros Kanban',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mensagem Rápida',
                'verbose_name_plural': 'Mensagens Rápidas',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('is_secret', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'verbose_name_plural': 'System Settings (Legacy)'},
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='ai_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='resolution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whatsappconnection',
            name='color',
            field=models.CharField(default='#7c3aed', max_length=7),
        ),
        migrations.AlterField(
            model_name='chatbotconfig',
            name='model',
            field=models.CharField(default='claude-sonnet-4-6', max_length=100),
        ),
        migrations.AlterField(
            model_name='conversationactivity',
            name='action',
            field=models.CharField(choices=[('opened', 'Aberto'), ('assigned', 'Atribuído'), ('transferred', 'Transferido'), ('status_changed', 'Status alterado'), ('note_added', 'Nota adicionada'), ('message_sent', 'Mensagem enviada'), ('closed', 'Fechado'), ('resolved', 'Resolvido'), ('reopened', 'Reaberto')], max_length=50),
        ),
        migrations.AlterField(
            model_name='conversationtag',
            name='conversations',
            field=models.ManyToManyField(blank=True, related_name='legacy_tags', to='atendimento.conversation'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('customer', 'Cliente'), ('agent', 'Atendente'), ('ai', 'IA'), ('system', 'Sistema'), ('internal', 'Interno')], max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='atendimento.category'),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='atendimento.company'),
        ),
        migrations.CreateModel(
            name='KanbanColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('color', models.CharField(default='#7c3aed', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='atendimento.kanbanboard')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='KanbanCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.IntegerField(default=0)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_cards', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanban_cards', to='atendimento.conversation')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='atendimento.kanbancolumn')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='conversations', to='atendimento.tag'),
        ),
        migrations.CreateModel(
            name='UserGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='atendimento.contactgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissão de Grupo',
                'verbose_name_plural': 'Permissões de Grupos',
            },
        ),
        migrations.CreateModel(
            name='ChatFlowSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('group_jid', models.CharField(db_index=True, max_length=255)),
                ('step', models.CharField(default='subject', max_length=50)),
                ('subject', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='atendimento.chatflow')),
            ],
            options={
                'indexes': [models.Index(fields=['group_jid'], name='atendimento_group_j_1441b8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='kanbancolumn',
            index=models.Index(fields=['board', 'position'], name='atendimento_board_i_8e8cae_idx'),
        ),
        migrations.AddIndex(
            model_name='kanbancard',
            index=models.Index(fields=['column', 'position'], name='atendimento_column__01b6db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usergrouppermission',
            unique_together={('user', 'group')},
        ),
    ]
