# Generated by Django 5.2.7 on 2026-06-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_category_chatflow_company_kanbanboard_quickmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentstatus',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Nome exibido nas mensagens enviadas pelo WhatsApp', max_length=100),
        ),
    ]
