# Generated by Django 5.2.7 on 2026-06-04 00:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0004_message_attachment_url_textfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendantContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Número no formato internacional, ex: 5511999999999', max_length=50)),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(blank=True, help_text='Conexão WhatsApp usada para enviar os lembretes', null=True, on_delete=django.db.models.deletion.SET_NULL, to='atendimento.whatsappconnection')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendant_contact', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contato do Atendente',
                'verbose_name_plural': 'Contatos dos Atendentes',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Andamento'), ('done', 'Concluída'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_conversations', to='atendimento.conversation')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_conversations', to='atendimento.task')),
            ],
            options={
                'verbose_name': 'Conversa da Tarefa',
                'unique_together': {('task', 'conversation')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='conversations',
            field=models.ManyToManyField(blank=True, related_name='tasks', through='atendimento.TaskConversation', to='atendimento.conversation'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', '-created_at'], name='atendimento_status_860fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='atendimento_assigne_cac82c_idx'),
        ),
    ]
