# Generated by Django 5.2.7 on 2026-06-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0005_task_attendantcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_task_conv',
            field=models.BooleanField(default=False, help_text='Conversa vinculada a uma tarefa — novas mensagens abrem novo chamado'),
        ),
    ]
