# Generated by Django 5.2.7 on 2026-06-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0006_conversation_is_task_conv'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='notif_aberto_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
