# Generated by Django 5.2.7 on 2026-06-26 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0007_conversation_notif_aberto_enviada'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatflowsession',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_sessions', to='atendimento.conversation'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('pre', 'Pré-abertura'), ('new', 'Novo'), ('open', 'Aberto'), ('pending', 'Aguardando'), ('resolved', 'Resolvido'), ('closed', 'Fechado')], default='new', max_length=20),
        ),
    ]
