# Generated by Django 5.2.7 on 2026-07-08 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0008_chatflowsession_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='csat_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='conversation',
            name='csat_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='csat_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text='Se preenchido, este chamado foi mesclado para outro (o destino).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_children', to='atendimento.conversation'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='sla_resolution_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='sla_response_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
