# Generated by Django 5.2.7 on 2026-07-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0009_conversation_csat_comment_conversation_csat_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='personal_wa_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
