# Generated by Django 5.2.7 on 2026-08-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0010_conversation_personal_wa_alert_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactgroup',
            name='auto_atendimento_excluido',
            field=models.BooleanField(default=False, help_text='Se marcado, este grupo nunca recebe auto atendimento — nem por um fluxo específico, nem pelo fluxo universal (group_ids vazio).'),
        ),
    ]
