# Generated by Django 5.2.7 on 2026-08-12 13:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0012_scheduledmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('emoji', models.CharField(blank=True, default='', max_length=32)),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('sender_jid', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('external_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='atendimento.message')),
            ],
            options={
                'verbose_name': 'Reação de mensagem',
                'verbose_name_plural': 'Reações de mensagens',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['message', 'created_at'], name='atendimento_message_379902_idx')],
            },
        ),
    ]
