# Generated by Django 5.2.7 on 2026-09-04 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0013_messagereaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMemberName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_names', to='atendimento.whatsappconnection')),
            ],
            options={
                'verbose_name': 'Nome de participante de grupo',
                'verbose_name_plural': 'Nomes de participantes de grupo',
                'unique_together': {('connection', 'jid')},
            },
        ),
    ]
