# Generated by Django 5.2.7 on 2026-09-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0014_groupmembername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationactivity',
            name='action',
            field=models.CharField(choices=[('opened', 'Aberto'), ('assigned', 'Atribuído'), ('transferred', 'Transferido'), ('status_changed', 'Status alterado'), ('note_added', 'Nota adicionada'), ('message_sent', 'Mensagem enviada'), ('message_edited', 'Mensagem editada'), ('closed', 'Fechado'), ('resolved', 'Resolvido'), ('reopened', 'Reaberto')], max_length=50),
        ),
    ]
