# Generated by Django 5.2.7 on 2026-09-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0015_alter_conversationactivity_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergrouppermission',
            options={'verbose_name': 'Atendente do contato/grupo', 'verbose_name_plural': 'Atendentes por contato/grupo'},
        ),
    ]
