# Generated by Django 5.2.7 on 2026-09-15 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0018_alter_conversationactivity_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_preview',
            field=models.CharField(blank=True, default='', help_text='Trecho da citação, para quando a mensagem original não está no CRM.', max_length=300),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_sender_name',
            field=models.CharField(blank=True, default='', help_text='Quem escreveu a mensagem citada, idem.', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='Mensagem citada, quando ela existe no CRM.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='atendimento.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to_external_id',
            field=models.CharField(blank=True, db_index=True, help_text='wamid da mensagem citada (mesmo que ela não esteja no CRM).', max_length=255, null=True),
        ),
    ]
